### ISSUE TITLE
Multi-key mappings don't register

### ISSUE THREAD

**Issue by bwhelm** [terrychou/iVim#1]
In my vimrc, I have single-character mappings that work just fine. But no multi-key mapping seems to work at all, which includes all `<Leader>` mappings: the first key gets ignored, and subsequent keys are taken as if the first key were not pressed. For example:

    nmap <Leader>m :messages<CR>

When I type my `<Leader>` key (currently set to `,`, but changing it doesn't seem to matter), nothing happens; when I then type `m`, Vim waits for another key so that it can set a mark.

Am I missing something?

I should add: This is a fantastic project, which greatly improves previous efforts. `idoc` and `ishare` work brilliantly. Congratulations on your work this far!

**Comment by terrychou** [comment]
Thanks for feedbacks! Yes, I am aware of this problem now, looking into it.
