### ISSUE TITLE
Using 'gx' to open url's in Markdown docs

### ISSUE THREAD

**Issue by mchalkley** [terrychou/iVim#100]
Is there a way to get gx to work with iVim?

Thanks,

Mark

**Comment by terrychou** [comment]
@mchalkley what exactly is `gx` here you refer to? More details would be great.

**Comment by mchalkley** [comment]
@terrychou  - Sorry, didn't mean to be too cryptic.  I use 'gw' on my Windows laptop to open URLs embedded in my Markdown documents.  It uses netrw, as I understand it...

Thanks,

Mark

**Comment by terrychou** [comment]
Since iVim already has the external command `open` available, all you need to do is to make it as the viewer command. You can do this in either of two ways:

1. put `let g:netrw_browsex_viewer='open'` into your `.vimrc` file;

2. uncomment and set the above settings via `:NetrwSettings`.

**Comment by mchalkley** [comment]
I chose to use your first option and it worked perfectly - thanks!

Mark

**Comment by terrychou** [comment]
@mchalkley no problem.
