### ISSUE TITLE
i found something inconvenient

### ISSUE THREAD

**Issue by namuelo** [terrychou/iVim#101]
i'm a newe in vim, and as i learn the very basics of it i try to use the editor, after some update i found this; 
i have an old iphone 5s with ios 12.4.5
as i remember when tap with two fingers the keyboard used to disappear and then if one scroll with two fingers the keyboard remained hide so contemplate the text is easy, most in small screens like mine, but after an update when scrolling with two fingers, after making the keyboard disappear, it reappears. so how to make it the old way, is my question.

**Comment by terrychou** [comment]
I will look into this.

**Comment by terrychou** [comment]
It's been fixed, and will be available in the next update.

**Comment by namuelo** [comment]
Thank you. I'm waiting that update eagerly.

**Comment by terrychou** [comment]
Version 2.16, which includes this fix, is now available.
