### ISSUE TITLE
Utilizing the whole screen area

### ISSUE THREAD

**Issue by vitalmsystems** [terrychou/iVim#103]
Dear Sirs and Madams,

    Can you hint at a setting to make panes utilize the whole screen area? The red line on the screenshots below.
![IMG_0150](https://user-images.githubusercontent.com/55534553/78220735-bd844700-74ca-11ea-9fb4-f31303e7df39.PNG)
![IMG_0151](https://user-images.githubusercontent.com/55534553/78220754-c6751880-74ca-11ea-9c5c-924a268e8f20.PNG)

Thank you.
Cheers!

**Comment by terrychou** [comment]
The "wasted" space at the bottom is caused by the height of the font you are using. The screen height is divided by the height of the font. However, when it reaches the bottom, the left space cannot fit a complete font height.

As to the rightmost part, it should be the scrollbar shown.
