### ISSUE TITLE
Which is the most compatible plugin manager

### ISSUE THREAD

**Issue by angarc** [terrychou/iVim#105]
I usually use vim plug, but I wasn't able to get it to work. I tried adding plugged.vim on the .vim/autoload/ directory, but when I ran `:PlugInstall` it said there was no command for PlugInstall.

It doesn't matter which one I use, just as long as I'm able to install some. Do you know of any that work?

**Comment by terrychou** [comment]
Most vim plugin managers utilize the external command `git`. Unfortunately, it is not available in iVim. As a result, you may need to copy the plugin files into their necessary positions by hand for now.

**Comment by angarc** [comment]
awesome, thanks
