### ISSUE TITLE
Ivim does not open...

### ISSUE THREAD

**Issue by weiszr** [terrychou/iVim#106]
Ivim does not open, neither from the desktop nor through share.

**Comment by terrychou** [comment]
More details would be more helpful. For example:

* which version of iVim are we talking about? iOS's version? Your device?
* what modifications (especially concerning iVim's configuration) did you make before the failure?
* Have you tried to launch iVim without reading rc files?

**Comment by terrychou** [comment]
I'll close this issue since it gets no further responses.
