### ISSUE TITLE
Build fails with "No such module 'ios_system'"

### ISSUE THREAD

**Issue by voltprime-b** [terrychou/iVim#109]
I'm trying to build iVim locally.

I cloned the repo (currently at 8a160df "Merge branch 'enableterm'") and switched it to my own team & group, but I'm stuck. It keeps complaining, "No such module 'ios_system'" in iVim/VimAppDelegate.swift.

Do you know how I can fix this?
<img width="1280" alt="Screen Shot 2020-04-24 at 10 12 23 PM" src="https://user-images.githubusercontent.com/64295690/80269857-fdc58800-8678-11ea-9cd8-960ca07871e0.png">

**Comment by terrychou** [comment]
Frameworks for external commands support are not contained in the repository. You need to download and deploy them from the release: https://github.com/terrychou/iVim/releases/tag/v1.0

**Comment by voltprime-b** [comment]
Thanks for the quick response. 
Unfortunately, it quickly ran into another error: "iVim/Resources/python: No such file or directory"
The Resources directory is missing, and I'm not sure how to fill in all its missing files. "python" seems simple enough, but then there's the commandDictionary.plist and extraCommandsDictionary.plist. I'm trying to follow holzschu's readmes in their repos, but no luck.

Do you know how to generate these too?

<img width="1011" alt="Screen Shot 2020-04-26 at 1 00 23 AM" src="https://user-images.githubusercontent.com/64295690/80299354-52403480-8759-11ea-9d96-45e95df5fcfe.png">

**Comment by terrychou** [comment]
Added the related resources to the release too. Download and deploy it.

**Comment by voltprime-b** [comment]
Thank you. I'm able to build now!
