### ISSUE TITLE
Is there a good way of detecting iVim/iOS from Vimscript?

### ISSUE THREAD

**Issue by sedm0784** [terrychou/iVim#11]
I currently share my `vimrc` across many devices, and, although *sharing* it will not be possible with iVim, I'd still like to be able to just copy it in whenever I make meaningful changes. I therefore need a way of detecting that I'm running in iOS.

I've come up with the following, which just catches the error thrown when running my usual OS detection code, but is there a better way?

    if has("unix")
      try
        let s:uname = system("uname")
        echom "NOT iVim"
      catch /^Vim\%((\a\+)\)\=:E484/
        echom "This is iVim"
      endtry
    endif

**Comment by bwhelm** [comment]
Try:

    :echo hostname()

iVim should return `iPad`.

**Comment by sedm0784** [comment]
Terrific. Thanks!
