### ISSUE TITLE
source ~/ivim/vimrc didn’t work

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#115]
It’s been working for a while, somehow it didn’t work and iVim go black and quit.
I tried change
```text
source ~/ivim/vimrc
``` 
to
```text
source ivim/vimrc
``` 
and rename ivim/vimrc to vimrc.vim then
```text
source ~/ivim/vimrc.vim
``` 
It still didn’t work.
Did I miss something?

**Comment by htkm** [comment]
cloud you try `:version` and come back with the output?

**Comment by suliveevil** [comment]
![version](https://user-images.githubusercontent.com/35763237/82882935-5a67db80-9f74-11ea-8be0-24a7103384f1.png)

It’s confusing me that at first time I setup step by step and it works somehow I added some submodules and iVim go black and stucked.

There is no warning or error to find out what is happening to iVim ,so I delete all the config.

Life is so hard on iPadOS……

**Comment by htkm** [comment]
So, the output reads like you can take off the `ivim` part of your source command. My understanding is you created `ivim` directory wanting to put your setup there. Is that right?

**Comment by terrychou** [comment]
It may have some problematic commands in the sourced file. It is hard to tell if we don't know its content.

**Comment by suliveevil** [comment]
I was using brettc’s solution to add plugins to iVim back then.
Now I give up using git submodule because Working Copy’s submodule sucks…

I’m using Vim8’s builtin package management now,and it works fine and plainly understandable than pathogen or dein.

I comment my solution to [issue-107](https://github.com/terrychou/iVim/issues/107)
