### ISSUE TITLE
Quit when at SplitView

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#116]
Would you please make the other app go into fullscreen instead of quit with iVim?
Thank you very much.

请问可以让 iVim 退出时让另一个 App 进入全屏模式而不是跟着 iVim 一起退出全屏吗？
万分感谢。

**Comment by htkm** [comment]
Hi, could you describe what else you have tried to do so?

**Comment by suliveevil** [comment]
> Hi, could you describe what else you have tried to do so?

Action:  use the `:q` to auit iVim.
Want:    Don’t want the other app quit with iVim.

**Comment by htkm** [comment]
I see. Could you tell me what happens if you do `:iopenurl working-copy://`?

**Comment by htkm** [comment]
I tried a-Shell to see what happens if I type exit in split window which made a nice transition for another window to take the rest. So I think `:iopenurl` might be useful in another case. What else can we try?

**Comment by suliveevil** [comment]
Thank your for your awesome reply.
Hope iVim will have this nice transition too.

**Comment by htkm** [comment]
In fact, there cloud be another way to achieve by using external keyboard such as Apple Magic Keyboard with little tweak.

Goto Settings - Accessibility - Keyboards - Full Keyboard Access toggled on,
Then bring up the Commands list section.
You will find `INTERACTION` group and `Actions` inside. This one gives users the ability to control "split-view and slide-over".

This solution has gone too far from `:q` If your continuity is important, this might be a worth consideration.

Looking for your feedback.

**Comment by suliveevil** [comment]
Thank you very much!
I will try it.

**Comment by terrychou** [comment]
The expected behavior requires an app to adapt the multiple windows feature in iOS 13. iVim hasn't made the adaption since it seems not so necessary (iVim already has its own windows management mechanism).

**Comment by suliveevil** [comment]
If iVim will quit the splitview without bring the other app along，
it will works better with other app，like Dash 、SiriShortcuts or someother apps.

**Comment by suliveevil** [comment]
Finally I understand what you have said.
The multiple windows feature means One app two window.

I will get used to live in iVim😝
