### ISSUE TITLE
Font Install Problem

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#117]
iPadOS 13.5

ERROR:failed to get text content from file ‘…’

![ERROR:failed to get text content from file ‘…’](https://user-images.githubusercontent.com/35763237/82978455-2f829380-a017-11ea-9a2c-02725c2389e9.jpeg)

**Comment by htkm** [comment]
Hi, could you share another capture to see which menu caused that error?

**Comment by suliveevil** [comment]
![Font Install Error](https://user-images.githubusercontent.com/35763237/83023729-e145b280-a05f-11ea-9dd0-8e703aaad955.png)

**Comment by suliveevil** [comment]
> Hi, could you share another capture to see which menu caused that error?

I add a new screenshot

**Comment by htkm** [comment]
Great. Could you try with the following capture?

<img width="540" alt="PNG image" src="https://user-images.githubusercontent.com/6189096/83109832-0b00e700-a0fd-11ea-8ab6-a355a6bac959.png">

**Comment by suliveevil** [comment]
There is no ”Open in iVim” in my sharesheet，only “iVim”.🤯

**Comment by htkm** [comment]
I believe you went through all of suggestions. Okay, how about trying the other way?

1. Run `:idoc` command to bring up file browser.
2. Go to your JebBrainsMono directory.
3. And pickup your font to install.

With my setup similar to yours, I was able to have the font installed.

Can you try this one more time? Hope that works.

**Comment by suliveevil** [comment]
Thank you very much, this is the solution!
