### ISSUE TITLE
Vim 8 builtin package management function doesn’t work sometimes

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#118]
I want to use Vim 8 builtin pakage management function

```text
$HOME/.vim/pack/foo/start/plugin-folder-or-repo/plugin/plugin-name.vim
``` 

Somehow it works for a while, then I add another plugin, it didn’t work and iVim stucked then it quit without wanring or some other information.

There must be wrong somewhere inside iVim, but I don’t know how to deal with or fix it.

**Comment by htkm** [comment]
I would like to guess outside 😃

Is it possible to have more information about the plugin sent you here?

**Comment by suliveevil** [comment]
It works, I figured it out.
In cmd mode input `scriptnames` then <kbd>Return</kbd>

> I would like to guess outside 😃
> 
> Is it possible to have more information about the plugin sent you here?
