### ISSUE TITLE
Git replacement

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#119]
Using dulwich (git implementation, pure python) as git will be great for plugin management.

**Comment by htkm** [comment]
I am curious about what kind of task requires Git and its replacement beside the plugin management. Just for that, could try `:h iplug` and share your experience? Thanks.

**Comment by suliveevil** [comment]
Tried `:h iplug` ,then I get 
```vim
E149: Sorry, no help for iplug
``` 
😂😂😂

**Comment by suliveevil** [comment]
Git is just a tool to sync plugin repos.
Since iVim have `python3` (and `curl`), dulwich will be a python version of Git.
Then we can sync/pull plugin repo from GitHub/GitLab/Gitee…

**Comment by htkm** [comment]
@terrychou could you estimate the time release of next version? Seems to me like `iplug` is only available in the test flight version.

**Comment by terrychou** [comment]
the new Plugins Manager `iplug` is right now in testing, it will be release soon.

**Comment by suliveevil** [comment]
🤩 🤩 🤩 this is great
