### ISSUE TITLE
iTunes File Sharing

### ISSUE THREAD

**Issue by lifepillar** [terrychou/iVim#12]
I do not see iVim listed among the apps in iTunes file sharing. I recall that the old Vim app had that feature. Is there a plan to add iTunes file sharing to iVim?

On a related note, what is the best way to transfer my .vim folder to iVim? With `:idocuments` command I seem to be able to import a single file at a time.

**Comment by terrychou** [comment]
iVim has not enabled the iTunes file sharing yet so far. It will be added.

Because `:idocuments` is mainly for file editing, it would be better to use the iTunes file sharing to transfer a bunch of files.

**Comment by lifepillar** [comment]
Thanks for the reply. I have used `:idocuments` to import my `vimrc` and a few other files. A bit laborious, but doable. Looking forward to seeing iTunes file sharing implemented!

**Comment by bwhelm** [comment]
This seems to work very nicely. I imported the .vim folder from my main computer, and everything copied well, including hidden files/folders, such as `.git` folders. (Exporting those hidden files/folders is another matter, but that may be an iOS/iTunes limitation.) With limited testing, I haven't encountered any problems.

**Comment by lifepillar** [comment]
I use the latest version from the App Store, and I do not see iVim in iTunes. @bwhelm Have you built iVim yourself?

**Comment by terrychou** [comment]
They are testing the beta version via TestFlight. If you have interest to take part, please give me your email.

**Comment by terrychou** [comment]
Enabled in version 1.12
