### ISSUE TITLE
function keys

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#121]
What is the best practice to remap a shortcut to a function key?

**Comment by htkm** [comment]
Like this?
`:nnoremap <F2> a<C-R>=strftime("%c")<CR><Esc>`

If you mean the shortcut by iOS, it would be like,
`:nnoremap <F2> :iopenurl shrotcuts://<CR>`

**Comment by suliveevil** [comment]
Thank you very much🥰🥰🥰
Only iVim/Vim could have all key codes on iPadOS!
