### ISSUE TITLE
SiriShortcuts App Support

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#122]
Wish iVim could have `Shortcuts Actions` in `Shortcuts App`

**Comment by suliveevil** [comment]
this is a-Shell’s `Shortcuts Action`
![a-Shell Shortcuts Action](https://user-images.githubusercontent.com/35763237/83193225-3b7e6a80-a169-11ea-9fc8-e48364b03538.png)

**Comment by htkm** [comment]
Interesting. Would you be able to describe a specific flow that could be useful with iVim's shortcut support?

**Comment by suliveevil** [comment]
Only if there is a way, there will be more possibilities:


-[ ] execute command

-[ ] get file

-[ ] output vim command result

**Comment by htkm** [comment]
As far as I can tell, iVim supports the launch options and I think you can start from there.
Have a look at `:h ios-settings`
With a specific arguments and `always` on, the possibilities can go far more.

And `iopenurl` in this practice looks like a nice option to return to the caller with the result of command.

**Comment by suliveevil** [comment]
Learned a lot about iVim from you😘😘😘
