### ISSUE TITLE
how to add plugins from file like Python’s pip install -r requirements.txt

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#123]

**Comment by suliveevil** [comment]
If there is a something like

```vim
iplug freeze > plugins.txt
iplug install -r plugins.txt
``` 

It will definitely be a game changer!

**Comment by htkm** [comment]
thanks for sharing a great idea. i wonder what if it would look like in nodejs culture. perhaps `:iplug yarn packages.json<cr>`?

**Comment by suliveevil** [comment]
Yeah, and JSON is awesome.
We may specify each plugin’s location(type folder) and other iplug `options`  in it!

**Comment by suliveevil** [comment]
made an example

```json

{
    "description":"iVim config",
    "author":"suliveevil",
    "repo":"github.com/suliveevil/vim_on_ipados",
    “.vimrc”:””,
    "ivim":[
        {   "name":"vim-which-key",
            "url":"",
            "autoload":"y"
        },
        {
            
        }     
    ],
    "language":[
        {
            "url":"",
            "autoload":"y"
        },
        "https://www.github.com/xxx/abc",
        "https://www.github.com/yyy/def",
    ],
    "completion":[
        {
            "name":"ultisnips",
            "url:""
        },
        {
            "name":"vim-snips",
            "url:""
        },
        {
            "name":"nerdcommenter",
            "url:""
        }      
    ],
    "code_display":[
            
    ],
    "integration":[
            
    ],
    "interface":[
    {
        "name":"lightline",
        "url:""
    },
    {
        "name":"nerdtree",
        "url:""
    }
            
    ],
    "commands":[
            
    ],
    "other":[
            
    ]

}

```

**Comment by terrychou** [comment]
The subcommands `export` and `import` will be added in the next version.

**Comment by suliveevil** [comment]
Wow! That would be awesome!

**Comment by terrychou** [comment]
subcommands `export` (`:h :iplug-export`) and `import` (`:h :iplug-import`) have been added to version 2.22(2) in TestFlight, please give them a try.

**Comment by suliveevil** [comment]
I just tried export and import, it works great.
Gitee is better than GitHub on this import from url thing.

Will iplug support import from file?

**Comment by terrychou** [comment]
By "file", do you mean that compressing a plugin into an archive file?

**Comment by suliveevil** [comment]
I mean `iplug import p.json` instead of `iplug import https://xxx.com/raw/master/p.json`.

If iplug can support local plugin file(vba or folder),that would be even nicer. Shougo's dein support local plugin, which means Git is not required.

**Comment by terrychou** [comment]
In fact, `iplug import` supports both local file and remote file. Please refer to `:help :iplug-export` and `:help :iplug-import`.

**Comment by suliveevil** [comment]
I should read the helpdoc thoroghly 😂
