### ISSUE TITLE
iplug quit when cloning

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#127]
✅ 45 plugin install with option `-q` test
❌ 45 plugins install without option test
```vim

iplug add https://github.com/majutsushi/tagbar https://github.com/preservim/nerdtree https://github.com/SirVer/ultisnips https://github.com/itchyny/lightline.vim https://github.com/preservim/nerdcommenter https://github.com/ryanoasis/vim-devicons https://github.com/Yggdroot/indentLine https://github.com/jiangmiao/auto-pairs https://github.com/lervag/vimtex https://github.com/justinmk/vim-sneak https://github.com/tpope/vim-repeat https://github.com/ludovicchabant/vim-gutentags https://github.com/prabirshrestha/vim-lsp https://github.com/kana/vim-textobj-user https://github.com/honza/vim-snippets https://github.com/liuchengxu/vim-which-key https://github.com/justinmk/vim-dirvish https://github.com/wakatime/vim-wakatime https://github.com/mg979/vim-visual-multi https://github.com/liuchengxu/vista.vim https://github.com/liuchengxu/eleline.vim https://github.com/mhinz/vim-signify https://github.com/dense-analysis/ale https://github.com/Shougo/deoplete.nvim https://github.com/easymotion/vim-easymotion https://github.com/vimwiki/vimwiki https://github.com/junegunn/goyo.vim https://github.com/itchyny/calendar.vim https://github.com/Yggdroot/LeaderF https://github.com/rafi/awesome-vim-colorschemes https://github.com/skywind3000/asyncrun.vim https://github.com/ncm2/ncm2 https://github.com/Shougo/defx.nvim https://github.com/prabirshrestha/asyncomplete.vim https://github.com/andymass/vim-matchup https://github.com/vim-syntastic/syntastic https://github.com/tpope/vim-commentary https://github.com/python-mode/python-mode https://github.com/kana/vim-textobj-fold https://github.com/jceb/vim-orgmode https://github.com/idanarye/vim-vebugger https://github.com/sbdchd/neoformat https://github.com/mhinz/vim-startify https://github.com/tpope/vim-surround https://github.com/ctrlpvim/ctrlp.vim

``` 

Quit when cloning,and `iplug list` say that I have 0 plugin installed.
But I can see 28 folders in `~/.vim/pack/ivim/start`
Test `:Goyo`  and the interface shows that plugin Goyo works.
Wired.

**Comment by suliveevil** [comment]
run cmd again and then I got this
![already exists、disabled](https://user-images.githubusercontent.com/35763237/83275226-78963b80-a201-11ea-8a7e-a05832d6a21b.jpeg)

**Comment by htkm** [comment]
Thanks for having a battle test!  I don't know much about how iOS works, my guess is that each app installed in iOS is sandboxed thus subject to unexpected result or even app termination when iOS thinks it's necessary to keep other apps working as designed.

But you are right, would you mind test with 30, 20, 10, and 5 plugins and comeback with the result? That might give a better coordination to someone trying to take this issue to a pull request.

**Comment by suliveevil** [comment]
Yeah, I can do this.Wait a minute.

**Comment by suliveevil** [comment]
29 plugin test,24 folders found,0 plugins on `iplug list` 
```vim

iplug add https://github.com/kana/vim-textobj-user https://github.com/honza/vim-snippets https://github.com/liuchengxu/vim-which-key https://github.com/wakatime/vim-wakatime https://github.com/mg979/vim-visual-multi https://github.com/liuchengxu/vista.vim https://github.com/liuchengxu/eleline.vim https://github.com/mhinz/vim-signify https://github.com/dense-analysis/ale https://github.com/Shougo/deoplete.nvim https://github.com/easymotion/vim-easymotion https://github.com/vimwiki/vimwiki https://github.com/junegunn/goyo.vim https://github.com/itchyny/calendar.vim https://github.com/rafi/awesome-vim-colorschemes https://github.com/skywind3000/asyncrun.vim https://github.com/ncm2/ncm2 https://github.com/Shougo/defx.nvim https://github.com/prabirshrestha/asyncomplete.vim https://github.com/andymass/vim-matchup https://github.com/tpope/vim-commentary https://github.com/python-mode/python-mode https://github.com/kana/vim-textobj-fold https://github.com/jceb/vim-orgmode https://github.com/idanarye/vim-vebugger https://github.com/sbdchd/neoformat https://github.com/mhinz/vim-startify https://github.com/tpope/vim-surround https://github.com/ctrlpvim/ctrlp.vim
```

**Comment by suliveevil** [comment]
![29 plugin test](https://user-images.githubusercontent.com/35763237/83315237-12390980-a251-11ea-850b-c7b897561c3b.jpeg)

**Comment by suliveevil** [comment]
BTW: I use this [Shortcuts](https://www.icloud.com/shortcuts/e9a0506773da4ad6ae5f837f6f0120ed) to test.

**Comment by suliveevil** [comment]
✅ 20 plugin test
```vim

iplug add https://github.com/liuchengxu/vim-which-key https://github.com/liuchengxu/vista.vim https://github.com/liuchengxu/eleline.vim https://github.com/mhinz/vim-signify https://github.com/easymotion/vim-easymotion https://github.com/junegunn/goyo.vim https://github.com/itchyny/calendar.vim https://github.com/rafi/awesome-vim-colorschemes https://github.com/Shougo/defx.nvim https://github.com/prabirshrestha/asyncomplete.vim https://github.com/andymass/vim-matchup https://github.com/tpope/vim-commentary https://github.com/python-mode/python-mode https://github.com/kana/vim-textobj-fold https://github.com/jceb/vim-orgmode https://github.com/idanarye/vim-vebugger https://github.com/sbdchd/neoformat https://github.com/mhinz/vim-startify https://github.com/tpope/vim-surround https://github.com/ctrlpvim/ctrlp.vim

```
![20 plugin test](https://user-images.githubusercontent.com/35763237/83315382-30533980-a252-11ea-8785-9c349a72d402.png)

**Comment by suliveevil** [comment]
❌ 25 plugins test
installed 21，3 faild due to http error,1 missing
`iplug list` couldn’t correctly show them.
![25 plugins test](https://user-images.githubusercontent.com/35763237/83315758-bd978d80-a254-11ea-8aa6-448f013f3b2b.jpeg)

**Comment by suliveevil** [comment]
✅ 20 plugin test
```vim

iplug add https://github.com/liuchengxu/vim-which-key https://github.com/liuchengxu/vista.vim https://github.com/liuchengxu/eleline.vim https://github.com/mhinz/vim-signify https://github.com/easymotion/vim-easymotion https://github.com/junegunn/goyo.vim https://github.com/itchyny/calendar.vim https://github.com/rafi/awesome-vim-colorschemes https://github.com/Shougo/defx.nvim https://github.com/prabirshrestha/asyncomplete.vim https://github.com/andymass/vim-matchup https://github.com/tpope/vim-commentary https://github.com/python-mode/python-mode https://github.com/kana/vim-textobj-fold https://github.com/jceb/vim-orgmode https://github.com/idanarye/vim-vebugger https://github.com/sbdchd/neoformat https://github.com/mhinz/vim-startify https://github.com/tpope/vim-surround https://github.com/ctrlpvim/ctrlp.vim

```
![20 plugin test](https://user-images.githubusercontent.com/35763237/83315382-30533980-a252-11ea-8785-9c349a72d402.png)

**Comment by suliveevil** [comment]
✅ 10 plugins test

```vim
iplug add https://github.com/majutsushi/tagbar https://github.com/Yggdroot/indentLine https://github.com/liuchengxu/vista.vim https://github.com/liuchengxu/eleline.vim https://github.com/junegunn/goyo.vim https://github.com/itchyny/calendar.vim https://github.com/Shougo/defx.nvim https://github.com/prabirshrestha/asyncomplete.vim https://github.com/python-mode/python-mode https://github.com/ctrlpvim/ctrlp.vim 
```

**Comment by suliveevil** [comment]
20 or 10 is just ok for iplug to deal with, I won’t test 5 again.

**Comment by terrychou** [comment]
Thanks for this pressure test, it is very helpful. By "quit", do you mean "iVim crashes"? Also, right now, `iplug` doesn't implement background tasks, so it wouldn't work if you switch away from iVim while `iplug` is working.

`iplug` summarizes and records installed plugins at the end of whole operation, so if the adding fails, there would be zero plugins recorded.

**Comment by htkm** [comment]
> BTW: I use this [Shortcuts](https://www.icloud.com/shortcuts/e9a0506773da4ad6ae5f837f6f0120ed) to test.

I was amazed by reading your shortcut which made me feel your overwhelming energy towards iVim. Inspired by you, I came up with an idea that might be able to support you hence the community. Let me allow a few hours. Thanks guys I was boring Saturday but no more.

**Comment by suliveevil** [comment]
Yes, too many plugins installing simutanously makes iVim crash.
> By "quit", do you mean "iVim crashes"?

**Comment by suliveevil** [comment]
I made this Shortcuts using [Dictionary Action Builder](https://routinehub.co/shortcut/4626)

**Comment by terrychou** [comment]
@suliveevil would you try the "45" one with the option `-q`? It won't show the progress view but will give a short notification at the end of the whole operation. If this succeeds, it would something wrong with the progress view...

**Comment by suliveevil** [comment]
I made Vim assistant by using this [Dictionary Action Builder](https://routinehub.co/shortcut/4626) Shortcuts.

 > [Vim assistant](https://www.icloud.com/shortcuts/e9a0506773da4ad6ae5f837f6f0120ed)

**Comment by suliveevil** [comment]
Yeah,wait a minute.

> @suliveevil would you try the "45" one with the option `-q`? It won't show the progress view but will give a short notification at the end of the whole operation. If this succeeds, it would be something wrong with the progress view...

**Comment by suliveevil** [comment]
> @suliveevil would you try the "45" one with the option `-q`? It won't show the progress view but will give a short notification at the end of the whole operation. If this succeeds, it would be something wrong with the progress view...

Install with option `-q` works great and didn't crash,only the unknown waiting and progressing bothered me.

**Comment by terrychou** [comment]
I also tested the "45 bunch". Rather than crashing, it was that some plugins took longer because of the network condition. Which made the whole operation look not so fluent.

**Comment by suliveevil** [comment]
Yeah,Install with option `-q` is great, it would be better if there has a notification for each one plugin as a `-n` option or some othername.

But these 45 plugin crashes my iVim and I have to reinstall, which part I don’t understand.

**Comment by terrychou** [comment]
Actually, if adding with option `-q` or the progress view is dismissed by touching the `Done` button, there will be a notification shown after the whole operation. But it seems too short to stand out.

**Comment by suliveevil** [comment]
`-q` is great, and if there is a `-n` which means nontification for each one plugin insntalled will be better.

**Comment by htkm** [comment]
![iplug iOS notification](https://user-images.githubusercontent.com/6189096/83329350-f589e980-a2c3-11ea-8b30-6ce4c9d117c7.gif)

This. You guys are making a fantastic progress. I am not sure if the GIF posted as well.

**Comment by suliveevil** [comment]
Notification is great!

**Comment by htkm** [comment]
@terrychou I realize something by seeing iOS notification brings the "seamless" or "continuity-like" user experience into the iVIM workflow. I don't think this is just a feature added to be able for casting a spell on **_@the-shortcut-wizard_**.

Seems to me like this has unlocked something enlightened and you probably noticed what that is 😃

**Comment by terrychou** [comment]
Another advantage of the system notifications is that they are also available as history for reference.

**Comment by htkm** [comment]
Great. Could you say a little more on history and reference?

**Comment by terrychou** [comment]
@htkm By that, I mean: https://github.com/terrychou/iVim/issues/133#issuecomment-636333854

**Comment by htkm** [comment]
Ah, okay thanks for the reference. Thinking about utilizing the system notification in iVim makes me think greedy.

**Comment by terrychou** [comment]
In version 2.22(2), I fixed a possible bug for this crash. Has the crash ever happened again?

**Comment by suliveevil** [comment]
Havn't test it, I'm a little tired of Install&Uninstall thing.
Maybe I should just use Import&Export.
