### ISSUE TITLE
iplug local plugin and vim.org download url and vba and zip file support

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#128]
like dein , not vim-plug

**Comment by suliveevil** [comment]
like dein , not vim-plug

**Comment by terrychou** [comment]
Actually, this was in the original plan. But it was dropped for a better implementation. I will think about it.

**Comment by suliveevil** [comment]
Lets say I have a plugin under dev,
I just want put it under `~/.vim/pack/dev/start/` 
Wish iplug automatically scan and deal with it.

**Comment by suliveevil** [comment]
Like generate help doc、update changed doc

**Comment by suliveevil** [comment]
vba is great for some plugins which the author doesn't use GitHub/GitLab/Gitee…

http://www.drchip.org/astronaut/vim/index.html#WHEREFROM

https://www.vim.org/scripts/script.php?script_id=1203
