### ISSUE TITLE
iVim crashes on omni-completion with syntaxcomplete#Complete()

### ISSUE THREAD

**Issue by lifepillar** [terrychou/iVim#13]
To reproduce:

```vim
:set omnifunc=syntaxcomplete#Complete
```
Then start typing something and trigger omni-completion (`<c-x><c-o>`). iVim crashes immediately.

**Comment by terrychou** [comment]
The new version 1.10 has been just released on the App Store, I think it has already solved this problem. Update and give it a try.

**Comment by lifepillar** [comment]
Yes, that's fixed. Great job thanks!
