### ISSUE TITLE
Run ictags like a External Command

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#130]
How to run `ictags` like a External Command?
So that I don"t have to change plugins like Vista.vim、LeaderF、Tagbar，just `let g:tagbar_ctags_bin='ictags'`

**Comment by terrychou** [comment]
The `ictags` was added before the "external commands" idea, maybe I should change it to an external command completely.

**Comment by suliveevil** [comment]
I forked https://github.com/drbarrett/tagbar and made a PR, it conflicts with the https://github.com/majutsushi/tagbar/pull/611

Is there a way to use ictags without changing tagbar’s code?

**Comment by terrychou** [comment]
https://github.com/terrychou/iVim/issues/135#issuecomment-640974973
