### ISSUE TITLE
Python Module：pynvim、Greenlet Support

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#131]
I want to use Defx and it requires other two plugin and Python Module `neovim` whose dependencies are `pynvim` `greenlet`
Is it possible to integrated these modules into iVim?

**Comment by htkm** [comment]
`Defx` sounds cool tough I have no idea about it. How does it work? and what kind of problems does it solve?

**Comment by suliveevil** [comment]
It is a file browser, like NERDTree but more powerful.

**Comment by terrychou** [comment]
@suliveevil have you tried to install modules with `pip`?

**Comment by suliveevil** [comment]
Yeah, and it failed.
Seems the installing needs gcc and some other tools.
I’m not familiar whth gcc and make😂😂😂

**Comment by suliveevil** [comment]
After run `pip3 install msgpack`
`the folder you are executing pip from can no longer be found` occurs while run `pip3 install pynvim`

**Comment by terrychou** [comment]
Yeah, there is a problem that the working directory changes after a `pip` installation sometimes.

**Comment by suliveevil** [comment]
😂😂😂
I found out that only greenlet needs gcc.
Would you please integrated greenlet msgpack and pynvim into iVim so that we can use Shougo's newest plugins?

**Comment by suliveevil** [comment]
Would you please make pynvim or at least greenlet integrated into iVim?
I want use Shougo's plugins.

**Comment by htkm** [comment]
Hm..thinking about iVim is a sandbox app some library could require too much resource or too many precompiled dependencies. One day I wanted to see if `pyarrow` has no problem to install. It did not going well. I don't know. To me, support of `pypy`, `cffi`, `ipython`, `pandas`, `pyarraow`, `numpy`,`scipy` all in one in iVim is the ultimate setup but it's just my personal desire which won't fit in sandboxed app.

`msgpack` sounds very nice and useful indeed, but once iVim gets `msgpack` capability, would it be the next step to suggest the async communication between iVim and plugins like neovim?

**Comment by suliveevil** [comment]
iVim's Python can install msgpack, but what I need is pynvim(requires greenlet).

**Comment by terrychou** [comment]
If it is only one module, I will try to integrate it.

**Comment by suliveevil** [comment]
Shougo's plugins need pynvim, while pynvim requires msgpack and greenlet.
Only the greenlet is not pure python module, we may only need to integrate `greenlet` then we will got pynvim by pip.

**Comment by terrychou** [comment]
working on `greenlet`, can you provide me a simple script that can test it whether it is integrated successfully?

**Comment by suliveevil** [comment]
```python
from greenlet import greenlet

def test1():
    print(12)
    gr2.switch()
    print(34)

def test2():
    print(56)
    gr1.switch()
    print(78)

gr1 = greenlet(test1)
gr2 = greenlet(test2)
gr1.switch() 
``` 

The output should be "12 56 34"

**Comment by terrychou** [comment]
`greenlet` has been integrated, I will push a version to TestFlight for you to test.

**Comment by suliveevil** [comment]
Can't wait to see.

**Comment by terrychou** [comment]
> Can't wait to see.

It should be already available. Please check your email.

**Comment by suliveevil** [comment]
I‘ll install it.

**Comment by suliveevil** [comment]
The url link seems broken, `this build is no longer available` .

**Comment by terrychou** [comment]
> The url link seems broken, `this build is no longer available` .

Added your email again for this build, please try.

**Comment by suliveevil** [comment]
Switching to Shougo's plugins is painful. I'm about to giving up.
Anyway,greenlet is awesome, plugins with chain dependencies sucks!

**Comment by suliveevil** [comment]
For someone who want use pynvim:

```python
pip3 install pynvim --nodeps
pip3 install msgpack
```
