### ISSUE TITLE
iplug Notification instead of Popup Window or -q

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#133]
If there is a notification when a plugin is installed，that would be better than -q or Popup Window.

**Comment by suliveevil** [comment]
Notification is great!

**Comment by suliveevil** [comment]
![45 plugins test](https://user-images.githubusercontent.com/35763237/83330091-988c3480-a2bf-11ea-9e9a-82186eb9115d.png)

**Comment by htkm** [comment]
looking at the capture above, part of me feels wow but the rest thinks the other way. anyways- this is awesome!
