### ISSUE TITLE
iplug enhancement: search and install

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#134]
Search by plugin name
Sort by github repo star or other arguments
Install by <kbd>CR</kbd>

**Comment by htkm** [comment]
Hm...wonder if this is not something urgent so that we can take to study. What do you think? Not sure if the pieces to write the recipe is good enough. At least `:term` has `curl`, `sort`, `grep`, `sed` and so on...with GitHub API.

**Comment by suliveevil** [comment]
> Hm...wonder if this is not something urgent so that we can take to study. What do you think? Not sure if the pieces to write the recipe is good enough. At least `:term` has `curl`, `sort`, `grep`, `sed` and so on...with GitHub API.

I will try to learn and use this tools you mentioned😂

**Comment by htkm** [comment]
I am with you. But to be honest, I have no idea how to get the pieces together 😭

**Comment by suliveevil** [comment]
Just like a Web Scrapper，get repos url from web pages，and choose one append to `iplug add`

**Comment by htkm** [comment]
Sounds like `curl` is the first one comes into play.

**Comment by suliveevil** [comment]
Yeah，`curl` get web page then `regexp` get urls.

**Comment by htkm** [comment]
how can i make a http get for github search api? couldn't afford time to find related resources. mind giving me a hand?

**Comment by suliveevil** [comment]
I have no resources  either.
But I’m using Working Copy as a Git repo Download Tool.

**Comment by terrychou** [comment]
I think this would be better the job for a script. Don't forget that Python is also at your hand here.

Also, `iplug` does not aim only to Github. It supports other git repositories hosting services too.

**Comment by suliveevil** [comment]
I prefer Vim8’s builtin package manager now.
Somehow iVim couldn’t recognize the `~/.vim/pack/xxx/start/` any more.
