### ISSUE TITLE
Universal-CTags integration

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#135]
Is it possible to integrate Universal-CTags into iVim？

**Comment by terrychou** [comment]
Is it that it is not completely compatible with ctags?

**Comment by suliveevil** [comment]
😂Just a wander.
ictags is good enough for me.

**Comment by terrychou** [comment]
`ctags` has been changed to an external command and implemented from `Universal Ctags`. I have pushed it (ver 2.22(1)) to TestFlight, please have a try.

**Comment by suliveevil** [comment]
😂 I lost my TestFlight, would you please invite me again? 
Thank you very much.
suliveevil@icloud.com

**Comment by suliveevil** [comment]
Great feature! Now we can use official tagbar!

**Comment by terrychou** [comment]
Please test the new command `ctags` more. Because I don't use it much, I haven't tested it thoroughly.

**Comment by suliveevil** [comment]
`ctags -R .` works fine, this is all I need😂
Somehow `vim-gutentags` is not working.

**Comment by suliveevil** [comment]
I just find a plugin can generate tags without ctags.
It use regex to math `class` `function` `expression` and so on.
I will try to make a python generate script.

**Comment by suliveevil** [comment]
It's wired that I couldn't find a plugin automatically generate and update tags file.
Ctags tag file is important  and I will keep looking and testing some tag plugins.

As for iVim's universal-ctags, I haven't find a bug, so I will close this issue.
