### ISSUE TITLE
curl Crashes iVim

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#137]
`:!curl -v -k https://docs.python.org/zh-cn/3.8/archives/python-3.8.3-docs-text.zip `

**Comment by terrychou** [comment]
@suliveevil would you try this in `ivish`?

Also, I see a few crash reportings in TestFlight. Are they related to the `iplug` manager, or to the incompatible plugins you installed?

**Comment by suliveevil** [comment]
I stripped unnecessary  plugins from 51 to 29, but they made iVim unstable still.
I will restructure and test all scripts/plugins from scratch.
It could take a while since I just begin to learn and write VimL.

**Comment by suliveevil** [comment]
A list to show famous plugins that could be used in iVim will be helpful.
I will try to find out the most robust  dependency-less compatible plugins.

**Comment by suliveevil** [comment]
Confused to `:!` and `:ivish`, is there any difference?

**Comment by terrychou** [comment]
The unfortunate truth is, that `iplug` just provides a more convenient way to manage plugins, but it cannot guarantee a plugin's full functioning in iVim.

Normally, a plugin may not work as it advertises, but it should not "crash" iVim. The probably cause would be it calls an external command which iVim does not offer.

It would be great that we can make a compatible plugins list for iVim. Please take your time experimenting with it.

**Comment by suliveevil** [comment]
I will test some plugins,but I will use as less as possible plugins/scripts.
For example, I wouldn’t test NERDTree because it defines it shortcuts logic while Vim already has netrw.
`vim-vinegar` is what I’m using now.
For the heavy plugins like UltiSnips ALE, it may out of my capabity to test for now, I will keep it as long as it works.

**Comment by terrychou** [comment]
> Confused to `:!` and `:ivish`, is there any difference?

`:!` means to run an external command from the Ex command line. On the other hand, `ivish` is a very simple shell that runs in vim's internal terminal. The latter can utilize the advantages a terminal has to offer, such as colors, terminal ansi code etc.

**Comment by suliveevil** [comment]
Both `:!ls -la` and `:ivish `+` ls -la` shows something like `[1m[34m.[39;49m[0m` .

**Comment by suliveevil** [comment]
But when using vim-floaterm ,it disappeared.

**Comment by terrychou** [comment]
You need to use `ivish` in a terminal. `:shell` will open a terminal with `ivish` ready.

The seemingly weird part `[1m[34m.[39;49m[0m` is the ansi code for colors. It will only be translated in a terminal.

**Comment by suliveevil** [comment]
I got it.
`:ivish` take me to the Middle Tier, this is why I saw those `wired` display.
`:shell` or `:!` take me to the place I really want.

**Comment by terrychou** [comment]
Back to the problem itself, the command in question does crash iVim. The reason is because the command will try to output non-text content (binary content of the zip file) into the command line, which iVim fails to handle.

**Comment by suliveevil** [comment]
Would you please add a FileType Detection for command line mode ?
If there are something like `s[ave]  |  S[ave as]  |  d[elete]  `, that would be even better!

**Comment by terrychou** [comment]
> Would you please add a FileType Detection for command line mode ?
> If there are something like `s[ave] | S[ave as] | d[elete] `, that would be even better!

I don't quite understand this. Would you give some examples?

**Comment by suliveevil** [comment]
Sorry for the misunderstood.
I messed up Vim Ex-mode、Vim-cmdline-mode、External-Terminal-ivish😂😂😂
