### ISSUE TITLE
how to input an accented mark ` in iVim？

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#138]

**Comment by terrychou** [comment]
Do you mean the backtick `` ` ``?

**Comment by suliveevil** [comment]
Yes😂  backtick

**Comment by terrychou** [comment]
iVim does not put the backtick into the default extended keyboard. But you can use `:isetekbd` to customize your extended keyboard to whatever style you prefer.

**Comment by suliveevil** [comment]
Great feature!
