### ISSUE TITLE
Difficulty pinching to set font size

### ISSUE THREAD

**Issue by RafalLukawiecki** [terrychou/iVim#141]
Perhaps it is only me, so apologies for the generic title of the issue, but I am finding it very hard to set the font size using the pinch gesture because it moves through the value range much too fast. It takes less than 1mm of a finger movement for font size to change from 12 to 20, and since the progression is non-linear, it gets either huge or tiny very quickly.

Also, I find that the pinch gesture often starts when I am scrolling (two-fingers)—as a result my scrolling is interrupted and everything gets very big or very small. :)

Would it be possible to somehow make the pinch gesture harder to activate? Or perhaps to disable it?

Many thanks.

**Comment by terrychou** [comment]
Yeah, I also realize that the pinch-to-zoom is too sensitive. I will look into this.

**Comment by terrychou** [comment]
It's been made less sensitive and an option in Settings.app to toggle it has been also added. It will be available in the next update.

**Comment by RunningUtes** [comment]
Thanks for this. I have been looking for a way to disable the two finger font changing option in iVim. I find that I rarely want to change the font size and instead just want to scroll the text using two fingers instead.

**Comment by RafalLukawiecki** [comment]
Thank you, @terrychou, looking forward to trying it.

**Comment by terrychou** [comment]
@RafalLukawiecki no problem. I will push it to the TestFlight first. If you would like to try it beforehand, just drop me an email address.
