### ISSUE TITLE
Two Finger Swipe as Cursor or Mouse

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#142]
Would iVim support two finger swipe as cursor or mouse？

**Comment by suliveevil** [comment]
<kbd> Left </kbd>
<kbd> Down </kbd>
<kbd> Up </kbd>
<kbd> Right </kbd>

**Comment by htkm** [comment]
My understanding is that a two finger gesture should make a cursor move instead of the screen scroll. Is that right? I am not sure if this feature is configurable.

**Comment by suliveevil** [comment]
Sorry for not explicitly stating the “two finger gesture”.
It’s a feature of iPadOS and only works at the On Screen Keyboard area.
I will upload a picture.
![two-finger-swipe](https://user-images.githubusercontent.com/35763237/83855332-7f193b80-a74a-11ea-90ea-3ef5c8658668.png)

**Comment by terrychou** [comment]
I didn't know about this feature. Is it also available on iOS system other than iPadOS?

Of course I would like to add it into iVim. However, I am not sure that there is an open API for this or not, I need to do some research first.

**Comment by suliveevil** [comment]
I only have a iPad😂

**Comment by htkm** [comment]
I never knew the screen keyboard can do that. Interesting. For the record, my iPhone 6 version 12.4.6 doesn't that.

**Comment by suliveevil** [comment]
I’m using iPadOS 13.5.1.

**Comment by terrychou** [comment]
This is called `Virtual Trackpad`. It is also available on iPhones but you need to 3D touch to activate it. Unfortunately, I had no luck to find APIs for this.

**Comment by suliveevil** [comment]
This is wired.
