### ISSUE TITLE
Can’t complete any in-app upgrades/purchases

### ISSUE THREAD

**Issue by abrookins** [terrychou/iVim#143]
Hi!

Love this app. I’d like to donate to it and also unlock features like Auto Restore and the plugin manager.

However, every time I try to donate or buy any of these upgrades, I tap the price and get a spinner that never completes.

![89C90E6E-3D23-4AC3-9267-346C34134F63](https://user-images.githubusercontent.com/97182/84085410-68692380-a99a-11ea-98ef-c6131f536f93.jpeg)

Help me pay you!

I’m on iOS 13.5.1, an iPad Pro 11 (2020), on a good wifi connection.

**Comment by terrychou** [comment]
Glad to know that you love iVim and thanks for supporting!

The spinner means that iVim is trying to connect to Apple's purchasing server and if it never stops, there would probably be some problem with the connection. Normally, if it is connected, it will prompt you to sign in your Apple ID to confirm the purchasing.

Don't worry, this happens. I suggest that you can sign out of your iTunes account on the device and sign in again to see whether it improves. Or you can try it at another time.

**Comment by abrookins** [comment]
Well, I could never get it to work in my iPad, but I did on my iPhone. Thanks, Terry!

**Comment by terrychou** [comment]
You're welcome, Andrew. Thank you for supporting again.
