### ISSUE TITLE
iVim not showing up in Files app

### ISSUE THREAD

**Issue by jeffgravitywell** [terrychou/iVim#144]
Hi, 
I recently purchased iVim and got the iOS file sharing working locally but the folder doesn't appear in the Files app (or sync anywhere else it seems).  If I do a search in FIles for iVim, it finds the app folde.  When I open the folder, it shows me the files I created. The issue is that these files don't appear anywhere else.  Am I missing something with setup?

**Comment by ewok** [comment]
I’ve update iVim today on v2.22 and now I don’t see iVim folder in “On my iPhone/iPad” section. It disappeared =((

I was using WorkingCopy to sync files which I was editing. Now I am not able to do that.

Could you say, it is an expected behavior or not?

**Comment by terrychou** [comment]
This is weird. v2.22 didn't make any change concerning this part. Have you encountered this issue on other devices?

**Comment by ewok** [comment]
@terrychou Thank you for the tip! I tried to install it on my iPhone and all works as expected.
Then I reinstalled it on my iPad and nothing happened.
And just in case I rebooted the iPad and the folder came back.
I suspect this is kind of iOS glitch.
Sorry for disturbing you!

**Comment by terrychou** [comment]
@ewok no problem. Glad you get everything back.
