### ISSUE TITLE
【Terminal Enhancement】CPR(cursor position requests)

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#145]
Run IPython needs CPR.
![run IPython needs CPR](https://user-images.githubusercontent.com/35763237/84321866-90c56d80-aba6-11ea-99b7-8e8ee98a49fe.png)

**Comment by terrychou** [comment]
It is kind of weird because the internal terminal window should support CPR.

Did you install IPython via pip?

**Comment by suliveevil** [comment]
Yes, I run `pip3 install ipython` to use IPython as REPL.

**Comment by htkm** [comment]
I ran into this. I think he is right. Let me see if I can make some gif.

**Comment by htkm** [comment]
![Image-3](https://user-images.githubusercontent.com/6189096/84498346-79dc6380-aceb-11ea-9ba4-09f124e9c9a4.gif)

**Comment by suliveevil** [comment]
Everytime using ipython will get a `;1R` 

Every first time using ipython will get an error.
Every second time and delete the `;1R` then IPython works.

![scond time works](https://user-images.githubusercontent.com/35763237/84499357-08011b80-ace5-11ea-97e3-a0af91c92d0a.png)

**Comment by suliveevil** [comment]
Video is here:

https://github.com/suliveevil/ivim_rc/blob/master/resources/iVim-IPython.mp4

**Comment by suliveevil** [comment]
a-Shell have a similar bug before https://github.com/holzschu/a-shell/issues/63

**Comment by terrychou** [comment]
Thanks for these feedback, I will look into this.
