### ISSUE TITLE
Python Module, LeaderF

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#146]
I want use LeaderF as replacement of Ctrlp,
but LeaderF doesn’t work.

AttributeError: module ‘os’ has no attribute __getattr__

![module ‘os’ has no attribute __getattr__](https://user-images.githubusercontent.com/35763237/84387427-8c8c6500-ac25-11ea-8253-48a7abdb55d6.png)

**Comment by terrychou** [comment]
LeaderF makes its fuzzy engine by making a C extension (https://github.com/Yggdroot/LeaderF/blob/master/autoload/leaderf/fuzzyMatch_C/setup.py). This is not supported in iVim unfortunately.

**Comment by suliveevil** [comment]
C is optional, not required.

**Comment by dangh** [comment]
+1 for this. LeaderF fuzzy is much better than CtrlP
