### ISSUE TITLE
What is the default set of isetekbd in dict format?

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#149]

**Comment by terrychou** [comment]
You can restore to the default config at any time by running `:isetekbd default`. If you are really curious about it, you can refer to the source code: https://github.com/terrychou/iVim/blob/fe7a03e485da96544c747e9fbf87a32235f171be/iVim/ExtendedKeyboardManager.swift#L260

**Comment by suliveevil** [comment]
Wow, thank you very much. I will try to make a <kbd>Meta/Alt</kbd> key
