### ISSUE TITLE
permanent link to outside directories

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#152]
Would that be possible to make a permanent link to outside directors like Textastic does? 
So we can edit files in Working Copy without open it.

![Textastic](https://user-images.githubusercontent.com/35763237/84779224-b4f5d400-b016-11ea-9cc1-e5752a51c7d1.jpeg)

**Comment by terrychou** [comment]
I have also been thinking about this. Give me more time.

**Comment by suliveevil** [comment]
I'm installing the 2.23-2, exciting moment!

**Comment by ewok** [comment]
Could you say, when you plan to update it in AppStore?

**Comment by terrychou** [comment]
@ewok it's been submitted to AppStore and under reviewing, should be available soon.
