### ISSUE TITLE
What is the maximum memory that iVim can use on Device？

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#153]
I have a plugin(ZFVimIM) could read files for chinese character input.
When I put a db file(filetype is text, largefile.txt) contains 3 million words (about 80MB), it crashes iVim.

**Comment by htkm** [comment]
Wow. I think I had a similar experience. My guess that the max memory changes over time managed by OS. After the crash, I thought if iVim was compiled with `clientserver`, we could have remote machine do the heavy lifting.

But I wasn't sure if that options is for this case. The remote vim is probably not another iVim of course, meaning that there's no limit in plain vim configuration. Sometimes I do `:term ssh ...` then open another vim in remote feeling awkward.`+clientserver` can help me fix my habit?

**Comment by terrychou** [comment]
The `maximum memory` that iVim can use differs device by device and it also depends on the memory usage of the whole system. Therefore, it is not something iVim can predict or enforce by code.

Would you share the plugin and the database in question, so that we can have a try?

**Comment by suliveevil** [comment]
## Plugin:

https://github.com/ZSaberLv0/ZFVimIM

## Data:

https://github.com/suliveevil/pyim-greatdict.vim

I couldn't locate where the problem happends, memory limit is just a guess.

**Comment by suliveevil** [comment]
I give up using ZFVimIM temporarily.
It couldn't handle large files like thesaurus_query.vim.
