### ISSUE TITLE
【ripgrep integrate】

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#154]
Would that be possible ？
https://github.com/BurntSushi/ripgrep

> It is built on top of Rust's regex engine. Rust's regex engine uses finite automata, SIMD and aggressive literal optimizations to make searching very fast

**Comment by terrychou** [comment]
`ripgrep` is written in Rust. Even though it is not impossible, I would try it maybe in the future.

**Comment by suliveevil** [comment]
Looking forward to the day😍
