### ISSUE TITLE
Open html in Safari

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#156]
Is there a way to open html in Safari ?
Like this `:!openurl file:///private/var/mobile/Containers/Data/Application/D8F8FD33-A3C1-4605-B6C1-39E9AEC246AC/Documents/awesome-plugins-ivim.md.html ` or something similar.

Or we only can do that by build a server using python then `:!openurl http://127.0.0.1/………` ?

**Comment by htkm** [comment]
Nice idea. I sometimes do this.
```
:term ++hidden python3 -m http.server 80<cr>
:iopenurl http://localhost<cr>
```
And there is `index.html` at `~` to help me see more.

**Comment by suliveevil** [comment]
Great approach!
