### ISSUE TITLE
【golang rust ruby wasm, make, cmake】

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#158]
Would those be possible？

a-Shell can install wasm like Vim install plugin.
There are some awesome plugins using ruby golang rust.
I want ivish can have those feature/use those plugins too!

**Comment by suliveevil** [comment]
## Plugin's Dependency Tools using rust:

https://github.com/nickspoons/vim-hotfuzz https://github.com/sharkdp/fd

## Plugin's Dependency Tools using golang:

https://github.com/itchyny/vim-gof https://github.com/mattn/gof

**Comment by ViViDboarder** [comment]
Do all of those actually require rust / go / or cmake, or is it only required to compile during install? If the latter, the binary could be pre-compiled and then installed without bringing the entire build deps.

**Comment by suliveevil** [comment]
## Language

language environment is actually required by plugins write with certain language.

## CLI

### maje cmake

make cmake are required to compile during install.

### wasm

wasm is what a-Shell using.

> If the latter, the binary could be pre-compiled and then installed without bringing the entire build deps.

**Comment by terrychou** [comment]
> Do all of those actually require rust / go / or cmake, or is it only required to compile during install? If the latter, the binary could be pre-compiled and then installed without bringing the entire build deps.

Due to the restriction of iOS systems, even the pre-compiled binaries need to be integrated into the main one (or some even needs certain modification) to run. Code that needs compiling to binaries is different from scripting languages like Python (`wasm` is closer to `Python` in this respect). So this is more difficult than it looks.

**Comment by dsisnero** [comment]
+1 for ruby

**Comment by dsisnero** [comment]
can we get ruby so it is a scripting language like python
