### ISSUE TITLE
Font Family Support

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#159]
Some Font is not a single ttf or otf file, would iVim support Font Directory ?

**Comment by suliveevil** [comment]
![font family](https://user-images.githubusercontent.com/35763237/85936937-d23d7300-b931-11ea-83b9-acf157e8b188.png)

**Comment by terrychou** [comment]
`iVim` supports the fonts collection format `ttc`, you can try that.

**Comment by suliveevil** [comment]
I will learn how to combine font files into single ttc.
