### ISSUE TITLE
Is it possible to delete a directory?

### ISSUE THREAD

**Issue by sedm0784** [terrychou/iVim#16]
I created a directory which I no longer require. Deleting files in netrw by pressing `D` works fine, but attempting to delete this directory results in the message `Cannot fork` followed by a string of errors.

I'm guessing this is because netrw somehow deletes files directly (perhaps with `delete()`?) but deletes directories by attempting to shell out, which fails because this is not supported in iVim.

IIRC I could delete the directory via iTunes File Sharing (once that's available in the App Store version!) but is there any way of deleting it from iVim itself?

**Comment by terrychou** [comment]
I think you need to empty the directory first before you can delete it via netrw.

**Comment by lifepillar** [comment]
I have tried `call delete('.vim/some/empty/dir')`, and it fails returning `-1`.

Other file operations, fail, too, like moving files.

**Comment by sedm0784** [comment]
As far as I'm aware, the directory *is* empty: I deleted all the files that I put in there, and netrw doesn't display anything in that directory.

**Comment by sedm0784** [comment]
> I have tried call delete('.vim/some/empty/dir'), and it fails returning -1.

I think that function can only delete files, not directories. On the version of Vim on my computer, it has an extra `flags` argument that can be used for deleting directories, but the iVim version doesn't seem to include this flag.

**Comment by terrychou** [comment]
@sedm0784 which version were you talking about?

**Comment by sedm0784** [comment]
@terrychou Not sure to what your question refers. The issue as reported exists in the current App Store version of iVim. I can add more details of the precise error messages if the issue is _not_ as simple as I suggested and if you want to look into it.

The `flags` argument to `delete()` is present in Vim 7.4 with patches 1-2196. I'm not sure when it was introduced.

**Comment by terrychou** [comment]
I see that vim of version 8 has this `flag` available, so I guess it may not be possible to delete a directory via a vim function before.

**Comment by sedm0784** [comment]
@terrychou Not sure if you misread my message. The new `flag` is present as of patch 2196 (i.e. before v8).

Regardless, since I opened this issue, you've enabled "File Sharing", and IIRC this means I should be able to delete the empty directory via iTunes, so I'm closing the issue.

**Comment by terrychou** [comment]
@sedm0784 No, I didn't misunderstand you. I know that you said it was a patched version for 7. By what I replied, I meant that I checked the version 8 and found that it had that available. Since it was added, it means that there wasn't alternative way to fulfill the function.

**Comment by sedm0784** [comment]
For posterity's sake, I just looked it up, and it looks as though the `flag` parameter was [added to `delete()` in patch 1107](http://ftp.vim.org/pub/vim/patches/7.4/README). (The latest patch iVim includes is patch 900.)
