### ISSUE TITLE
【Change InputMethod when enter InsertMode】

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#160]
That would be the best feature for non-English user。

**Comment by htkm** [comment]
I have thought about this. I wonder if ivim has an access to current state of  input method and also a permission to change that. It would be great to be able to see the name of current locale at some place.

**Comment by suliveevil** [comment]
Yes,permission is annoying.

**Comment by terrychou** [comment]
Unfortunately, for the sake of privacy and security, Apple doesn't provide public APIs for manipulating the input method.

**Comment by suliveevil** [comment]
Reading IM input is dangerous, but Change IM is not……
I tried several ways to input Chinese character : vimim、ZFVimIM…… without outer IME.
Maybe I should find a less complecated way to achieve my goal.
