### ISSUE TITLE
SSH argument to pass a specific port

### ISSUE THREAD

**Issue by htkm** [terrychou/iVim#161]
Is this possible for the ssh client to pass `-p` option for a specific port?

**Comment by terrychou** [comment]
Does specifying the port in the URL when connecting work?

**Comment by htkm** [comment]
<img width="981" alt="ssh report" src="https://user-images.githubusercontent.com/6189096/86246112-6e42d500-bbe5-11ea-92fd-489947f7bf14.png">

I was trying in a few ways. Not sure if this helps. Thank you.

**Comment by htkm** [comment]
<img width="546" alt="ivim-ssh-port-number-working" src="https://user-images.githubusercontent.com/6189096/88008338-0976fc80-cb4b-11ea-9d34-40dd54c4802a.png">

My test on the TestFlight 2.24(1) version worked well! I feel better with the ssh experience in regards to the terminal size. Thank you so much!

**Comment by terrychou** [comment]
Thanks for the feedback. Have you tried ports other than the default 22?

**Comment by htkm** [comment]
I haven't. Anyone else?

**Comment by htkm** [comment]
I have tried with non default port 2222 in my case.

`ssh ht@xxx.xxx.xxx.xxx:2222` works
`ssh -p 2222 ht@xxx.xxx.xxx.xxx` works

**Comment by terrychou** [comment]
@htkm Thanks, it is great to know this. I have pushed it to App Store, please let me know if you find further problem.

**Comment by htkm** [comment]
Thank you so much!
