### ISSUE TITLE
【pip upgrade】

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#162]
`pip3 install --upgrade pip`  is prohibited, would you please upgrade pip in iVim?

the default pip seems have some bug.

https://github.com/ionelmc/python-lazy-object-proxy/issues/42#issuecomment-650781115

**Comment by applesud** [comment]
@suliveevil Did you ever figure out a workaround for either of these problems?

**Comment by suliveevil** [comment]
I gave up using Vim plugins on iPadOS, dependency hell is painful.
