### ISSUE TITLE
【PythonModule: pyzmq】

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#163]
[jupyter-vim](https://github.com/wmvanvliet/jupyter-vim.git) needs jupyter which requires pyzmq.

The only problem to install jupyter is install pyzmq, just like greenlet to pynvim.

Would you please integrate pyzmq into iVim?

Install pyzmq needs the libcrypt-dev `brew install libcrypt-dev`.

https://github.com/zeromq/pyzmq

https://stackoverflow.com/questions/49805480/could-not-install-pyzmq-using-apt-pip-pip3-easy-install-etc-any-command?newreg=d0496c941c3c4db0a61ac1e877c2e41c

**Comment by terrychou** [comment]
`jupyter` is "interpreter-conuming", which means it needs several python interpreters running at the same time. In `iVim`, at most 2 interpreters can run simultaneously. So `jupyter` is not well supported.

**Comment by suliveevil** [comment]
I will use jupytext.vim  jupytext (python module)  Carnet and Juno (two Apps) instead.
