### ISSUE TITLE
【iexdir】failed create symlink

### ISSUE THREAD

**Issue by suliveevil** [terrychou/iVim#165]
Both of them failed:

```viml
ie add -o _exdir/PolyGit
ie add -o ../PolyGit
```

**Comment by suliveevil** [comment]
![failed create symlink](https://user-images.githubusercontent.com/35763237/86061625-a831a100-ba56-11ea-8760-07ab09426e43.png)

**Comment by terrychou** [comment]
this should be fixed in 2.23(3), and I have pushed it to TestFlight. Please give it a try.

**Comment by suliveevil** [comment]
Thank you very much.
