### ISSUE TITLE
Plugin Airline no longer works on iVim (iPadOS 14 beta 6)

### ISSUE THREAD

**Issue by agbohub** [terrychou/iVim#170]
It seems that the [Airline plugin](https://github.com/vim-airline/vim-airline) makes iVim stuck at load and render only a blank screen on iPadOS 14 beta 6.

The plugin worked well before I updated to beta 6. Note that it is featured in [Plugins which work well with iVim #147](https://github.com/terrychou/iVim/issues/147).

I wonder if anyone else is experiencing the same issue.

**Comment by agbohub** [comment]
P.S. iVim loads and works well when I disable the plugin in `.vimrc`.

**Comment by ericweir** [comment]
> On Sep 2, 2020, at 11:06 AM, agbohub <notifications@github.com> wrote:
> 
> 
> It seems that the Airline plugin makes iVim stuck at load and render only a blank screen on iPadOS 14 beta 6.
> 
> The plugin worked well before I updated to beta 6. Note that it is featured in Plugins which work well with iVim #147.
> 
> I wonder if anyone else is experiencing the same issue.

Not exactly the same issue, but the same response when I attempt to run a command of the Sessions app.

------------------------------------------------------------------------------------------
Eric Weir
Decatur, GA  USA
eeweir@comcast.net 

"(I)t is important that awake people be awake... the darkness around us is deep."

- William Stafford

**Comment by kuochang** [comment]
Have you guys install the official release of iOS 14 and the issue is still out there or not? I am afraid to install it and get my airline screwed up...:) Please let me know. Thanks!

**Comment by kuochang** [comment]
A quick update is that I just installed the official iOS14. It seems my airline works all right! FYI.

**Comment by agbohub** [comment]
> A quick update is that I just installed the official iOS14. It seems my airline works all right! FYI.

Thanks. Unfortunately on iOS 14 the plugin is still blanking out the app for me.

**Comment by terrychou** [comment]
I've fixed some problems in version 2.25. And one of them may probably be the cause of the recent failures of some plugins. I have pushed the updated version to App Store and it should be available soon.

Please tell me if it fixes the problem after you install it.

**Comment by agbohub** [comment]
> I've fixed some problems in version 2.25. And one of them may probably be the cause of the recent failures of some plugins. I have pushed the updated version to App Store and it should be available soon.
> 
> Please tell me if it fixes the problem after you install it.

Thank you Terry! With the latest version vim-airline and vim-airline-themes work perfectly well now.

**Comment by terrychou** [comment]
> Thank you Terry! With the latest version vim-airline and vim-airline-themes work perfectly well now.

You're welcome. Glad to know it fixes the problem.
