### ISSUE TITLE
Document from google-drive opened with idoc get closed after switching to another app

### ISSUE THREAD

**Issue by pasharik** [terrychou/iVim#177]
Hi,
I'm using google-drive to store text file with notes, which I'm taking while readging a PDF book in Adobe reader. May be in 20% cases when I swith back from Adobe reader to iVim, iVim get frozen for short time, and then text file closes. So blank document displayed instead, and I have to use `:idoc` to open document from google-drive again.

iPad mini 2
iOS 12.4.8

**Comment by terrychou** [comment]
How are you opening the text file from google-drive? via `:idoc`? Does google-drive support for third-party app to open its directories? If so, you can try and use `:iexdir` (see `":h :iexdir"`) instead. Right now, the latter is more robust than the former, especially in the case of files syncing with clouds.

**Comment by pasharik** [comment]
Yes, I'm using `:idoc`.
I just tried `:iexdir add` command - it opens dialog for choosing folders. Then I choose folder, click `Select` button, then `Done`, but nothing happend after that. Only thing I can do is do press `Cancel`. Then returned back to iVim, I type `:iexdir list`, but list is empty.
I tried it for google-drive and for iCloud-drive, in neither case wasn't able to add directory.
May be it's because my iPad is too old.

**Comment by terrychou** [comment]
In iOS 12, after you click the `Select` button and pick a folder, there should be an `Open` button besides `Done`. That would be the one you are looking for.

**Comment by pasharik** [comment]
Thank you! It worked for iCloud-drive, I was able to add directory. But for google-drive iVim gives error: 
```
Adding external directory failure
Failed to add external directory `Documents/Books`: failed to activate external directory
```
Probably google-drive doesn't support this feature.
I will look for other alternative file storage.
I think this ticket can be closed, as it's related only to google-drive?

**Comment by terrychou** [comment]
You're welcome. Then it looks like google-drive does not support other apps to open its directories. In that case, `:iexdir` would not work.

Please feel free to close this ticket whenever you feel proper. If you encounter further issue, you can reopen it or open another issue.
