### ISSUE TITLE
ANSI Color codes in Term

### ISSUE THREAD

**Issue by gkloss** [terrychou/iVim#178]
Hello iVim Team,

is it possible to get ANSI Color Codes working inside the iVim console?
I was launching a ptpython promt and got this screen.
![IMG_1658](https://user-images.githubusercontent.com/73476012/97173725-4e857d00-1791-11eb-8932-d811b14f9a22.PNG)

**Comment by terrychou** [comment]
It looks like you are running this in vim's cmdline, right? The ANSI code is supported in a term window. Try and launch one with `:sh`.

**Comment by gordonkloss** [comment]
Exactly! Will ANSI Color codes be supported in the cmdline? Running term window is working though.

**Comment by terrychou** [comment]
Because of the design and implementation, ANSI code support in the cmdline is not in the plan list. Besides, due to the difference between implementations of those two environments, running commands with ANSI code output in the term window would be more convenient and efficient.
