### ISSUE TITLE
Open-in-place and iOS11 document support

### ISSUE THREAD

**Issue by holzschu** [terrychou/iVim#18]
Would it be possible to have "open-in-place", so iVim can edit documents inside the cloud, or inside the sandbox of other apps? This really makes the editor more useful.

**Comment by terrychou** [comment]
See ":h :idocuments" for "open in place" in iVim. iOS 11 document support is in consideration.

**Comment by ckanthony** [comment]
it works perfectly, thanks for bringing this to us!

**Comment by terrychou** [comment]
Done in version 1.20
