### ISSUE TITLE
iOS Shortcuts support

### ISSUE THREAD

**Issue by 1dancook** [terrychou/iVim#180]
I'm unable to pass a file to iVim from iOS shortcuts. 

Ideally it would be good to for example:

- get a file from iCloud (get file action)
- pass the file to iVim (the Open In... action)
- edit file in iVim (and :wq)
- changes are reflected wherever that file is stored. 

This is a great app- thanks for all your work!

**Comment by 1dancook** [comment]
Might be duplicate or related to #172.

More info -
If I do the above shortcuts workflow I get a dialog to post text to iVim. But it doesn't work. (The interface itself doesn't work).

But that post text to iVim is not what I'm after- what I'm looking for is a way that we could share a file to iVim and iVim opens it up with the `:idoc` command.

**Comment by 1dancook** [comment]
I'm sorry. I should have investigated more.

The Shortcut actions of:
- get file (I'm using a file from Dropbox)
- open in...  (and select iVim as the app)

It does open in iVim, but what happens is that iVim creates a new file with the same contents and thus saving any changes is not reflected in the original Dropbox file.


What I expect to happen:

- the above type of workflow has the same essential behavior as the :idoc command

**Comment by terrychou** [comment]
Thanks for this suggestion. I will do some research on this too see whether `iVim` can provide some useful `Shortcuts` support.
