### ISSUE TITLE
iVim doesn't work anymore

### ISSUE THREAD

**Issue by ghost** [terrychou/iVim#188]
I'm so disappointed.  I loved iVim.  I'm not sure when it broke - iOS update?  I use an iPod running iOS 14.4.  Tonight I once again deleted iVim & reinstalled.  I had a daily journal in iVim - I loved the Shift+G command so I could go to the end of the file.  Plus I had scads of little notes organized in folders.  Now I'm using an app called TextEditor which I don't like nearly as much.  I think, if I recall correctly, iVim's simple text files lived without a file extension, whereas TextEditor requires the .txt extension.

The problem: I have text files in my iOS "Files" folder.  I used to simply tap the filename, & the file would open in iVim.  Now, when I tap a filename, not only is there nothing visible, but also, apparently I'm not actually "opening" the document I because all I can do from there is create a new document - no editing an old one.  The command :q is not accepted because If I do type something, then I have to use the command :wq and create a new document (e.g. [:wq Test1].    I can take that file to my desktop using the iPod to Mac desktop USB, and THEN I can open the file & see the text.  If I type text into the document using Insert mode, then input the :q command, I get the message "E37: No write since last change", even though I DID add text.  If I put in the command :wq I get the message "E2: No file name".  Do you know what might have happened, & how I can get back to using iVim?  I need the ability to edit on the iOs device.  Thanks-

**Comment by terrychou** [comment]
Could you please try not to "quit" iVim with ":q" and resign it by pressing the home button instead? Then try to open a file and see whether it works?

As to the errors, you can use the vim's help system to see what they mean (e.g. ":help E37"), it explains them very well.

**Comment by ghost** [comment]
Thank you so much for replying.
I tried pressing the Home button, as you suggested.  But then, the file is
not saved or exited; when I come back to iVim, no matter which file name I
choose in the iOs's "Files" folder, the same file that was previously open
is the one that displays.

I've tried various different things, but it's all so confusing.  For
instance,
I employed the [:w] command on a file named Test6, and pressed the Home
button.
I copied (dragged) this file to my desktop, via USB as I mentioned.  (I do
NOT use iCloud and hope to never do so.)
When I opened it on the desktop, Test6 appeared as it should, complete with
the text I input on iOs

I deleted Test6 from the iOS by selecting it on the device, & choosing
Delete.
I found the "Trash" folder in iOS & did a "final" (so I thought) Delete of
Test6.
I pressed the Home button.

On my desktop using Mac's TextEdit, plain text, I edited Test6.
I copied (dragged) the edited Test6 back to the iPod.
When I open the supposedly edited Test6, The UNEDITED original version,
with [<6C written] displayed at the bottom.

So there's something goofy going on in how iOS is saving a file that I've
deleted?  It also now seems that I'm not really exiting a file on the on
the iPod by pressing the Home button, and that I can only use that ONE file
- the one that I last edited.  And if I copy this file to the desktop, I
can't edit it there, and copy it back to the iPod - which is necessary, and
used to work.  If I use :wq or :q, then the pertinent file is no longer
available for me to open.

I haven't had trouble with understanding the error messages; I just gave
the numbers to you so you'd know which ones came up.

Any other ideas?
Thanks again,
Peggy

**Comment by terrychou** [comment]
Ok, let's make it simple: first, describe what are you expecting iVim to do (in a several-simple-steps example, nothing concerning the desktop transfer, which is sort of confusing:)); then tell me which of these steps not work properly now.

**Comment by ghost** [comment]
Spoken like a true programmer!
On my iOS 14.4 device (iPod), I expect to (and what used to happen):

   1. I navigate to the "Files" folder
   2. tap a document [e.g. Text6]
   3. Text6 opens in iVIm
   4. The body of the previously-entered text displays on the screen.
   5. I edit the body of the text.
   6. I enter the command :wq
   7. The document closes.
   8. I repeat steps 1 & 2 . . .
   9. Steps 4 thru 7 should be replicable

But no.  Instead, here's what happens:

   1. I navigate to the "Files" folder (same as before)
   2. tap a document [e.g. Text6] (same as before)
   3. A BLANK screen with no text on it displays (I don't know what
   happened to the previously entered text).
   4. I enter some text.
   5. Apparently, I've created a different document, as if I type the :wq
   command I am prompted to enter a filename.

How do I open, edit, and save Text6?

**Comment by terrychou** [comment]
What is the name of the BLANK buffer? (use ctrl+G to see)

Could you try the command `:idoc` to open the file? Let's see whether it works or not.

**Comment by ghost** [comment]
BLANK buffer: The message that came up was: "[No Name]" --No lines in
buffer--

I typed [:idoc test6] and got a blank screen.
I typed some text into the above blank screen
& tried [:wq]
"No filename" error.

Interesting, though: When I first tap the Text6 icon (the method that
formerly launched iVim when I tapped a ducment document in the iOS Files
folder), a file which I suspect is the top of the iVim help.txt file
flashes on the screen.  Though it doesn't quite resem

And, if I launch iVim and then type the command [:help], that file opens
just fine! help.txt, For VIM version 8.1, Last change: 2019 Jul 21
And I close that file just fine with [:q] as well.
Peggy

**Comment by terrychou** [comment]
Please see ":help idoc" first to learn how it works.

**Comment by ghost** [comment]
Well now.  On the iPod, if I tap the "Files" icon (see iPodScreen.jpg),
I get a "Browse" window, from which I select
On My iPod
where I select from Downloads, Firefox, or iVim.
Choosing iVim,  I see the documents test6 and test7.

So all I know how to do from there is tap a document icon, to open it.
But, it doesn't open; I just get the iVim screen, blank except that it
awaits my command or text entry.

Is this GUI the "document picker?"  And if so, the question remains: how do
I open the document?

[:iexdir list] brings up "0 link(s) found."
[:iedir fix] brings up "nothing to fix
[:iexdir files] brings up "nowhere to go"

The 2nd snapshot, iPodFiles.jpg, shows how, when I attempt to transfer the
files to my desktop, both iVim and TextEditor & iVim both have files
listed.  You can see those aforementioned created test6 and test7 in iVim,
and I can copy them to the desktop successfully and open them there - but I
can't open them on the iPod, once I've created them. Likewise, files that I
copy from the desktop to the iPod can't be opened, even though their icons
are visible.

If you're tired of considering this issue, please let me know & I'll stop
e-mailing you about it.  I did prefer iVim, when it was usable, to
TextEditor.

Thank you,
Peggy Richardson

**Comment by terrychou** [comment]
According to your description, the issue is "you cannot open files in iVim from the Files app on your iPod", right?

Please type ":help idoc" (not `iexdir`) to see how to use the command `:idocuments` to open files from the document picker. Whether it works or not is helpful to me to narrow the possible causes.

By the way, I am not seeing any of your screenshots here.

**Comment by ghost** [comment]
It takes me a while to get back to you.

I have certainly tried to understand the explanations to which ":help idoc"
points me, earlier in this saga.  ":help idoc" not illuminate for me what
the "document picker" is;
From the Help file: "Pick documents from iCloud Drive or other document
provider apps via the document picker" does not seem to apply.  Unless the
"Files" folder in iOs, which is where iVim saves all the iVim documents I
create, is a "document provider app."  And that's what doesn't seem to be
working?

In my e-mail, my screenshots show up in the e-mail I last sent you - maybe
you've got some sort of filter set?

Thanks,
Peggy

**Comment by ghost** [comment]
I thought you might be interested that finally stumbled across the answer -
at least, the one that works for me.

   1. If I tap on the iVim app icon on my iOs touchscreen, it opens an iVim
   window.  But to actually get any pre-existing document text to display on
   the screen, what I do is this:
   2. I tap on the small sphere in the upper right-hand corner.  (This
   sphere has 3 little dots in it).
   3. A menu displays.  One of the items in the menu is "Show me the
   documents", which I select by tapping on it.
   4. A list of documents displays.
   5. All I have to do then is select/tap the document I want to open, and
   off I go.

I'm so glad to have iVim functioning again.
Peggy Richardson

**Comment by suliveevil** [comment]
Open iVim -> type”:idoc” -> choose file to edit -> type “:wq”, this is the simplest workflow.

**Comment by ghost** [comment]
Yes, that's better than my kluge. Thx

**Comment by ghost** [comment]
Actually I double checked just now, & that doesn't work for me; I see a
nice GUI iocn for my document there after typing :idoc - but, when I touch
it (iPod touch, ios 15.1), I have the same problem as before - there's
nothing on the iVim interface until I follow the procedure of my 11/30/21
e-mail.
Peggy
