### ISSUE TITLE
External Monitor support broken in iVim 2.29

### ISSUE THREAD

**Issue by aaronhktan** [terrychou/iVim#190]
Hi,

I have been using iVim on an iPad connected to an external monitor via a USB-C adapter.

**Expected behaviour**: iVim is useable on an external monitor and appears the same way it appears on the iPad screen. This is how iVim behaved in version 2.28.

**Actual behaviour**: The iPad displays iVim like it used to, but the external monitor now only displays the file browser. The file browser also cannot be interacted with via keyboard nor Bluetooth mouse.

This is what I see on my iPad:
![IMG_1214](https://user-images.githubusercontent.com/14353716/108925794-3e7c8d80-760b-11eb-9a4f-b2f1af1518af.png)

This is what I see on my external monitor:
![IMG_1215](https://user-images.githubusercontent.com/14353716/108925807-44726e80-760b-11eb-8cb2-ba7002698acc.png)

Is it possible to restore the old method of handling an external monitor? Thank you!

**Comment by terrychou** [comment]
`iVim` adds support to multiple scenes since version 2.29. This seems the behavior of that mechanism.

Can you dismiss the file browser and leave only the main editor window, to see whether it works?

**Comment by aaronhktan** [comment]
I am unable to interact with the file browser at all. It is on an external monitor and does not allow input via keyboard nor mouse.

**Comment by terrychou** [comment]
Can you enter the App Exposé? Like long pressing `iVim`'s icon and select "Show all windows"?

**Comment by aaronhktan** [comment]
Here's what it looks like on the main iPad screen:
![image0](https://user-images.githubusercontent.com/14353716/108941427-16992400-7623-11eb-9e21-f6158deec97b.png)

And on the external monitor:
![IMG_1219](https://user-images.githubusercontent.com/14353716/108941442-1f89f580-7623-11eb-96d1-53208442f637.png)

**Comment by terrychou** [comment]
I am not familiar with external monitoring with an iPad. Is there any way to move an app's window to the external monitor explicitly? In our case, the main editor window to the external monitor?

**Comment by aaronhktan** [comment]
> Is there any way to move an app's window to the external monitor explicitly?

As far as I know, what gets sent to the external monitor is controlled by the app itself. For example, another app I use, Goodnotes, has settings that control what is sent to the external monitor.

![IMG_1220](https://user-images.githubusercontent.com/14353716/108944267-6af2d280-7628-11eb-8b26-8531673d1833.jpg)

I don't have any experience with iOS programming, but this documentation might help?
- https://developer.apple.com/documentation/uikit/windows_and_screens/displaying_content_on_a_connected_screen
- https://hacknicity.medium.com/external-display-support-on-ios-665cd1774511
- https://www.bignerdranch.com/blog/adding-external-display-support-to-your-ios-app-is-ridiculously-easy/

**Comment by terrychou** [comment]
Thanks for these informative links. I will do some researches to see whether I can do something with this issue.

**Comment by aaronhktan** [comment]
Thanks for the quick reply and for developing this great app!

**Comment by emkayonline** [comment]
I have this same issue (I have impaired sight so always use my iPad mirrored to a large external monitor)

I tried :ibrowse -l and it listed (something along the lines of)
com.terrychou.ivim Airplay (2-27).  Documents

I have had to type that from memory, because I made the mistake of typing :ibrowse -a com to activate it.

I am now stuck with iVim launching into a blank screen with no way out (I tried -U NONE, and disabled auto restore in settings, but that didn’t help). 

All I now get is that blank screen, with or without the external monitor plugged in. I’m guessing I may have to uninstall and lose my local configuration)

Anyway hope this information helps.

Thanks for a great app, I can’t wait to return to using it.

**Comment by terrychou** [comment]
@emkayonline Have you tried the long pressing iVim's icon and choose "Show All Windows" to manipulate the windows?

**Comment by emkayonline** [comment]
Brilliant! That just showed a single blank/black window - but using the + in the top RHS I was able to add a new window and kill the first one.

Thank you.

**Comment by terrychou** [comment]
@emkayonline You are welcome. Glad to know that it solves your problem. Also, thanks for your feedback and surely it provides helpful information.

**Comment by kuochang** [comment]
> Thanks for these informative links. I will do some researches to see whether I can do something with this issue.

I have the same issue as Aaron stated. I used external monitor to share my notes. Hopefully this can be fixed soon. Thank you in advance!

-Charles

**Comment by emkayonline** [comment]
For anyone who has this problem, and have iVim via TestFlight, then downgrading to 2.28 (3) you will find iVim is able to work again with an external monitor (including support for slide over and split screen on external monitors). The downside is there are only 38 days left on that version.

**Comment by terrychou** [comment]
I have restored the external display mirroring behavior. Would you like to help with testing it? If so, please offer me an email address for receiving the TestFlight invitation.

**Comment by emkayonline** [comment]
> restored the external display mirroring behavior

That’s exciting.  I’m more than happy to test (and also looking forward to testing the shortcuts integration). I’m martin{AT}livetheseasons.com

**Comment by emkayonline** [comment]
That’s looking great. It’s terrific to be able to use iVim again - thank you it is really appreciated.

I tried various combinations to break it with the external monitor mirroring (including opening file browser windows through exposé), and it worked perfectly.

A quick question (off topic) - how do I make an in app purchase to make a donation nowadays?

**Comment by terrychou** [comment]
@emkayonline looks like you are already in the testing group. Please install the version 2.30(2) and start testing.

**Comment by terrychou** [comment]
@emkayonline Great! I don't have an external display by hand, therefore your confirmation is very helpful, thank you. By the way, the new Shortcuts actions are also included since 2.30(1), you can try them too.

In-app purchasing is not included in the testing versions. In the App Store version, you can use ":isupport" to open the in-app purchasing options list :).

**Comment by terrychou** [comment]
I have published the fix in update 2.30 into App Store. I will close this issue and please let me know if any further problems come up.

**Comment by aaronhktan** [comment]
Can confirm that 2.30 fixed the issue, thank you for fixing so quickly!
