### ISSUE TITLE
[display issue] terminal

### ISSUE THREAD

**Issue by figuremout** [terrychou/iVim#191]
After enter terminal by `:ter` & close origin file by `:q`, the terminal can display on full screen. But when I ssh to remote host, the remote host command line can only display on **half screen**

**Comment by terrychou** [comment]
This happens because the window sizes are not updated as other platforms due to the signal handling.

**Comment by figuremout** [comment]
> This happens because the window sizes are not updated as other platforms due to the signal handling.

Thanks for reply, but I still can't figure out a way to solve this problem. Is it should blame on the remote host or vim, is there anything I can do to solve it?

**Comment by terrychou** [comment]
I guess what you want to achieve is to use `ssh` in a full window, right? If so, you can open a single terminal window in a new tabpage with `:tab term`.

**Comment by figuremout** [comment]
> I guess what you want to achieve is to use `ssh` in a full window, right? If so, you can open a single terminal window in a new tabpage with `:tab term`.

I have tried but it does not work, here is the screenshot. Thanks anyway
![IMG_20210310_002153](https://user-images.githubusercontent.com/44429569/110503052-c21f9980-8136-11eb-8f31-a232fda074df.png)

**Comment by terrychou** [comment]
Emm... it is weird because it works at my end.

According to your tabpage name, I think you connect `ssh` directly from the command. Could you try open the shell `ivish` first, then run `ssh` within it afterwards?

**Comment by figuremout** [comment]
Thanks a lot.  Both `:tab term` and typing with external keyboard are indispensable. I guess once the terminal is opened, its size is set and will not receive signals to change it. So its initial size may be squeezed by the origin file (when use `:term` to open terminal) or soft keyboard. And after origin file is closed and soft keyboard is hided, it still keeps the initial size.
