### ISSUE TITLE
how to install plug in without PlugInstall

### ISSUE THREAD

**Issue by gojekmaster** [terrychou/iVim#192]
now that PlugInstall can’t be used how can i install plug in ? if i have to buy the iplug i will but i dont know how to use it, can someone help me ?

thank you :)
ps. sorry for my bad english

**Comment by ericweir** [comment]
> On Mar 6, 2021, at 11:45 AM, gojekmaster <notifications@github.com> wrote:
> 
> 
> now that PlugInstall can’t be used how can i install plug in ? if i have to buy the iplug i will but i dont know how to use it, can someone help me ?

You will get a reference manual for the iPlug plugin.

WIAI, nothing wrong with your English.

------------------------------------------------------------------------------------------
Eric Weir
Decatur, GA  USA
eeweir@comcast.net 

"(I)t is important that awake people be awake... the darkness around us is deep."

- William Stafford

**Comment by gojekmaster** [comment]
can i install coc if i buy the iPlug plugin ? cosidering coc need nodejs to run

**Comment by terrychou** [comment]
Please see `:help iplug` for the details.

As to the plugin `coc`, if it depends on `nodejs`, then it will not work in iVim since `iVim` has no `nodejs` support yet.
