### ISSUE TITLE
Slow Input

### ISSUE THREAD

**Issue by GregoryShields** [terrychou/iVim#193]
First off, I'm grateful that this project exists at all, so please do not take my complaints as ingratitude.

Maybe it's just me, but when I type into iVim there is a very noticeable lag between the time I type the letter and the time it appears on my screen.

Is this normal? If so, then I can only imagine that there are some incredible inefficiencies somewhere in the translation to iOS.

Also, the screen on my iPad Pro has rounded corners. Since iVim uses screen coordinates, the character in the upper left corner gets cut off. It sure would be nice to inset the Vim interface a few pixels to prevent this.

**Comment by terrychou** [comment]
The only input lag I have encountered is right after switching `auto-restore` from `off` to `on`. Could you re-launch `iVim` or your device, to see whether this issue goes away?

As to the content inset, I will add an option in settings for you to customize them.

**Comment by GregoryShields** [comment]
Thanks for the feedback and your efforts, Terry.

I’ll try what you are asking.

**Comment by ahayman** [comment]
@GregoryShields I've found another issue with laggy text input here: https://github.com/terrychou/iVim/issues/194#issue-829205504

It's kind of a specific use-case (code folding for markdown), but if you do have that enabled, it could be part of the problem.

**Comment by terrychou** [comment]
@GregoryShields it ends up that instead of adding a setting option, I change to make `iVim` to automatically layout text to safe area on `iPad Pro`s. Would you like to have a test on this? If so, please give me an email address for me to send you a TestFlight invitation.

**Comment by GregoryShields** [comment]
Yes, Terry, that sounds great. Please send the invitation ***@***.***Thank you so much for your efforts.Sent via the Samsung Galaxy S8+, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Terry Chou ***@***.***> Date: 3/11/21  8:15 PM  (GMT-06:00) To: terrychou/iVim ***@***.***> Cc: Gregory Shields ***@***.***>, Mention ***@***.***> Subject: Re: [terrychou/iVim] Slow Input (#193) 
@GregoryShields it ends up that instead of adding a setting option, I change to make iVim to automatically layout text to safe area on iPad Pros. Would you like to have a test on this? If so, please give me an email address for me to send you a TestFlight invitation.

**Comment by terrychou** [comment]
@GregoryShields email seems starred out...

**Comment by GregoryShields** [comment]
I don't know what starred out means.I am also rather lost trying to make things happen on the iPad. I don't even know how I can upgrade or try out the experimental versions you are creating. Sent via the Samsung Galaxy S8+, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Terry Chou ***@***.***> Date: 3/16/21  12:25 AM  (GMT-06:00) To: terrychou/iVim ***@***.***> Cc: Gregory Shields ***@***.***>, Mention ***@***.***> Subject: Re: [terrychou/iVim] Slow Input (#193) 
@GregoryShields email seems starred out...

**Comment by terrychou** [comment]
I need one email address from you to send the TestFlight invitation. However, all the addresses in your messages look like `***@***.***`.

**Comment by GregoryShields** [comment]
Looks fine in my Sent folder. Anyway, I've attached an image of it.Thanks. Sent via the Samsung Galaxy S8+, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Terry Chou ***@***.***> Date: 3/21/21  10:12 PM  (GMT-06:00) To: terrychou/iVim ***@***.***> Cc: Gregory Shields ***@***.***>, Mention ***@***.***> Subject: Re: [terrychou/iVim] Slow Input (#193) 
I need one email address from you to send the TestFlight invitation. However, all the addresses in your messages look like ***@***.******".

**Comment by GregoryShields** [comment]
Somehow I had gotten it into my head that we were communicating via email. Ha! Anyway, obviously GitHub is going to obfuscate email addresses, which is a good thing. I'll look into private messaging via GitHub.

**Comment by GregoryShields** [comment]
Okay, I will send you an email at your public email address which is
terrychoucn@gmail.com

Thanks

**Comment by GregoryShields** [comment]
I sent you an email at your public email address which is
terrychoucn@gmail.com

Thanks

**Comment by terrychou** [comment]
@GregoryShields got it and invitation sent.

**Comment by GregoryShields** [comment]
It works great! No more slow input and no more cut off text. Thanks for sending me the iVim Beta, Terry. Thanks to Aaron for your feedback as well, though I did not look at the issue you mentioned.

I will be reading the iVim Help text and experimenting with getting my configuration (vimrc, etc.) integrated.

Sorry for me being slow in getting to this. I have some health issues.

**Comment by terrychou** [comment]
Great! I will include it in the next update to App Store. As to the slow reply, no problem and please take care.
