### ISSUE TITLE
<Ctrl> key is too sticky

### ISSUE THREAD

**Issue by bwhelm** [terrychou/iVim#2]
I understand the stickiness of the `<Ctrl>` key, but for my uses it's *too* sticky. Most of the time, when I enter a <Ctrl> command, I do it once and then go back no non-<Ctrl> commands. So for me, at least, it is annoying to have to swipe the `<Ctrl>` key, hit a normal key, re-swipe the `<Ctrl>` key, and get on with my editing. Would it be better to "release" the `<Ctrl>` key after the first <Ctrl> code has been entered? (This is what other iOS apps I'm familiar with do.)

Of course, this is largely a matter of personal preference, so feel free to just say "no".

**Comment by terrychou** [comment]
I have made the `<Ctrl>` key sticky like this because that there would be many cases when continuous `C-` are needed. And on iOS, it is not so convenient to hold a finger on the `<Ctrl>` key like we do on the real keyboards. By the way, to release the `<Ctrl>` key, a simple tap rather than a swipe will do. :)

**Comment by sedm0784** [comment]
FWIW, although I imagine I'll get used to it, I'd prefer a semi-sticky Ctrl key (that auto-releases after the first chord is typed) too. Consistency with the other apps I have that add keys like this would be helpful for my muscle memory and, for me, the number of times I need a single `C-` significantly outweigh the number of times I need a continuous `C-`.

Really, I think it should work exactly like the iOS Shift key: single tap for a single `C-` chord; double tap for `CtrlLock`.

**Comment by terrychou** [comment]
This is also becoming obvious to me. So I will reopen it as an issue, and try to make some improvements.

**Comment by lifepillar** [comment]
Alternatively to double tapping for stickiness (which might trigger Esc-Esc by mistake), I'd suggest the following: swiping Esc turns the key into sticky Ctrl (the current behaviour), but tapping and holding triggers a non-sticky Ctrl that lasts as long as the key is not released.

**Comment by lifepillar** [comment]
…or vice versa :) I see that in the current version Ctrl is not sticky any longer. But that makes some mappings a bit less convenient to type, like those for scrolling.

**Comment by terrychou** [comment]
Try to trigger the `ctrl` twice (drag-and-release twice) (:h ios-extended-keyboard)

**Comment by lifepillar** [comment]
I see. Ok, that's fine with me!

**Comment by sedm0784** [comment]
FWIW, the current behaviour is perfect for me!
