### ISSUE TITLE
support elixir files

### ISSUE THREAD

**Issue by ckanthony** [terrychou/iVim#20]
Please enable more file type to be able to open document picker,
I recently developing elixir files with .exs and .ex file extension.
It is grayed out in the document picker currently

**Comment by terrychou** [comment]
the coming update enables iVim to open all file types

**Comment by ckanthony** [comment]
please also enable folder, thanks!

Anthony

**Comment by terrychou** [comment]
Enable folder? Do you mean open a folder in iVim?

**Comment by ckanthony** [comment]
yes, then i can use :e to access the file in a project, that will be so good

Anthony

**Comment by terrychou** [comment]
This seems not feasible in the current implementation of iVim. But I will give it a consideration.

**Comment by ckanthony** [comment]
This is very powerful, please do give it a consideration

Anthony

**Comment by terrychou** [comment]
The folder opening feature has been added and under testing. Please see: https://github.com/terrychou/iVim/issues/43#issuecomment-376788694

**Comment by ckanthony** [comment]
Omg this is game changer!

Anthony
