### ISSUE TITLE
URL scheme support

### ISSUE THREAD

**Issue by jakub-stastny** [terrychou/iVim#200]
Hey,

I don't know whether it's just me missing something, but I read the manual and searched the GH issues and I can't find any info about _whether iVim supports iOS URLs_?

What I mean is I'd like to open URL say `ivim://my-documents/my-document.txt` for instance via a notification. I have a scheduled notification in Scriptable, which when I tap can execute a URL and that URL is meant to open iVim with a predetermined document.

The document is already in iVim directory, I'm not importing anything from outside.

Is there no such thing or is it just me?

*Alternatively* is there any other way to achieve similar results? I tried in Shortcuts `Run Ex Command`, I created a new command in my `~/.vimrc`: `command OpenJournal cd ~/hyperlinks/journal | edit journal.org`, but the shortcut only displays success and exits, I suppose it's meant for non-interactive things(?)

Thank you for any advice 🙏🏼

**Comment by terrychou** [comment]
Unfortunately, no, `iVim` right now does not support URL schemes as you described above. And due to the `Shortcuts`'s 10 seconds limitation, the `iVim`'s actions will run in background and then go back to `Shortcuts`.

However, I think there is a solution to your requirement. Although `iVim` jumps back to `Shortcuts` right after running the command, it usually still stays in the background. So you can use the action `Open App` to open `iVIm` right after the `Run Ex Command`.

**Comment by jakub-stastny** [comment]
@terrychou thanks! It did help, although curiously enough I had to go the other way: first `Open app`, then `Run Ex Command` (which gets executed after these 10 seconds).

Just wondering, is there any plan for supporting the aforementioned URL schemes in the future?

Thanks for iVim!

**Comment by terrychou** [comment]
@jakub-stastny glad to know it helps. 

As to the URL schemes support, I would prefer to implementing functionalities in `Shortcuts` unless it has to be done in the URL schemes way. If you have any suggestions, just let me know. :)

**Comment by jakub-stastny** [comment]
@terrychou may I ask why the preference for Shortcuts?

The way I see it, URL schemes are the most independent thing, it's the easiest one for integration (easy to integrate into Shortcuts as well as into Scriptable or Pythonista).

For instance in my workflow, I only ever use Shortcuts when there's something Scriptable cannot do (certain features of notifications for instance).

- Scriptable is JS -> I can have all my code in Git. Not being able to do so is simply not acceptable and this thing on its own is a sufficient reason for me to only ever use Shortcuts if there's no other alternative. So then obviously in Scriptable I need the URLs to work, otherwise I have to write a wrapper Shortcut and call it with `shortcuts://run-shortcut`, which then launches the Shortcut app (which does annoy me) and only then iVim[1].
- Obviously other people are using other alternatives such as Pythonista, so they also rely on URL schemes.
- People who are not even scripting can use URL schemes: for instance the task manager Things can have a URL (to any app) in a task description. Being able to do that is a big win in my opinion, I'd certainly use it.
- And very importantly – widgets. I can (and do) write widgets in Scriptable. And I happen to need to open iVim from my widgets, since they are things like logging my progress throughout the day, journaling, that sort of stuff. There is no way to write widgets in Shortcuts (and probably never will be), so one has to be using something like Scriptable. OK, I can still use a wrapper Shortcut that only calls iVim, but that means I'm introducing an external dependency to my code (that I can't put into version control in a reasonable way) and besides, all that app switching when I click on a widget (first it launches Scriptable, then Shortcuts, then iVim ... bloody hell, it's like a disco).

[1] And still – as it is now (meaning what we discussed in the previous comments about using `Open app` and all) is a workaround, it's fine for now, but either way what many people I suspect would want is a synchronous action for opening a desired file – and URL schemes sound natural fit for it in my opinion.

I do think having Shortcut actions is a good thing and the Shortcut actions that are already there make perfect sense, but I do not believe that they substitute the need of having URL schemes.

Anyway that's just my personal opinion. Would love to know your thoughts.

**Comment by terrychou** [comment]
@jakub-stastny I don't dislike URL schemes. Actually, my another app `Locu` is right based on it. The reason I choose `Shortcuts` over it is because there seems not so many users are really using it (according to my personal experience).

However, your points above are persuasive. I will consider about it when I have time. And it would be great if you have any specific suggestions and let me know.

**Comment by sedm0784** [comment]
It'd be really nice if you could pass command line options (in particular `-c` or `+` options) via a URL scheme.Failing that I'd like to be able to run Vim and open a file in a given location

**Comment by sedm0784** [comment]
It'd be really nice if you could pass command line options (in particular `-c` or `+` options) via a URL scheme.

Failing that, I'd like to be able to run Vim and open an existing file in a given location, and perhaps also open a new file with contents passed in as a parameter.

**Comment by jakub-stastny** [comment]
@terrychou I see, that's interesting. I really do believe it'd be worthy feature, especially since there are things that Shortcuts simply cannot do (for instance opening an URL from a task manager, as I described above). Especially in iVim, which is an editor for programmers, I'd really assume many people would prefer Scriptable or Pythonista over Shortcuts, as it's just more natural for programmers to use. Don't get me wrong, I don't want to bash the Shortcuts integration, I think it's great it's there, but I personally do miss URLs schemes.

As for specific suggestions, it'd be great if it could open documents from various locations: not only "On my iPad", but preferably also iCloud Drive and others – Working Copy for instance, that'd be extremely helpful.

![IMG_3199](https://user-images.githubusercontent.com/60524926/121409378-0fbec480-c927-11eb-9097-a6f1544788d8.jpeg)

To me personally, support for various locations would be on top of my wish list, although just supporting URLs within iVim's document directory would do as well.

Another half-fledged ideas:

- Maybe there could be `cd` parameter to `cd` into the project directory? If I want to edit a file, I most likely want to be in the project root, so for instance: `ivim://working-copy/blog/src/App.elm?cd=working-copy/blog`.
- Maybe we want to support opening multiple buffers/tabs? Although this could be over the top for simple URL schemes and in this case maybe using Shortcuts would be the best solution? On the other hand, Shortcuts will run iVim in the background, so the whole work around with `Open App` is necessary, which is not intuitive, plus there's the 10s timeout.

These are just some ideas. From my perspective I'm more than happy with having the most basic solution that could be iterated upon down the road, no need for perfection from the get-go.

Thank you for considering it!

**Comment by terrychou** [comment]
I have just added the custom URL scheme support into `iVim`. If you have interest in trying or testing it before the formal release, just let me know.

**Comment by sedm0784** [comment]
Yes, I'm definitely interested!

**Comment by terrychou** [comment]
> Yes, I'm definitely interested!

Leave me an email address so I send you a TestFlight invitation.
