### ISSUE TITLE
iexdir cannot access other "locations" 

### ISSUE THREAD

**Issue by kflu** [terrychou/iVim#201]
In Files app, other locations like OneDrive, or iCloud Drive cannot be accessed with `iexdir add`. These locations are grayed out. However, this is important because normally synced notes are put at those locations rather than a local directory.

* iphone 12 pro
* 12.5.1
* iVim 2.31(4) patches 1-2110

![image](https://user-images.githubusercontent.com/1031978/117867149-d4a87300-b24c-11eb-8504-b8a9e42de468.png)

**Comment by kflu** [comment]
.

**Comment by terrychou** [comment]
I think we are talking about the command `iexdir`, right?

I don't know why this happens on your device. But according to my test, at least the `iCloud Drive` is available to me (I am not using `OneDrive`).

**Comment by kflu** [comment]
> I think we are talking about the command `iexdir`, right?

Yes sorry for the typo.

> I don't know why this happens on your device. But according to my test, at least the `iCloud Drive` is available to me (I am not using `OneDrive`).

Right, later I fixed iCloud too. However, all other cloud services as I tested (OneDrive, Google Drive, Box.net, Dropbox) non of them are supported - i.e. they are all grayed out. iCloud is Mac ecosystem only - I guess nobody uses iCloud outside apple devices.

**Comment by f1se4** [comment]
I have tested with ipad-air 4. With icloud and Working Copy (excelent to have git workflow with ivim edition :P), and both works fine.

**Comment by kflu** [comment]
> I have tested with ipad-air 4. With icloud and Working Copy (excelent to have git workflow with ivim edition :P), and both works fine.

yeah maybe I wasn’t clear in the original post - this is less about iCloud but other cloud storages more in general, which allows you to access data across different platforms, like onedrive, google drive, dropbox, etc. Most of them have well supported FUSE on non-apple systems. 

Problem with iCloud+working copy for me is that it requires multiple apps to work in accordance to get the basic task done. 

iVim is just so amazing and useful I love it. But TBH I grew more and more disappointed at Apple’s closeness

**Comment by f1se4** [comment]
> > I have tested with ipad-air 4. With icloud and Working Copy (excelent to have git workflow with ivim edition :P), and both works fine.
> 
> yeah maybe I wasn’t clear in the original post - this is less about iCloud but other cloud storages more in general, which allows you to access data across different platforms, like onedrive, google drive, dropbox, etc. Most of them have well supported FUSE on non-apple systems.
> 
> Problem with iCloud+working copy for me is that it requires multiple apps to work in accordance to get the basic task done.
> 
> iVim is just so amazing and useful I love it. But TBH I grew more and more disappointed at Apple’s closeness

For me ivim is really great, and quick if you try ish and vim the performance is far far away. With git binaries and support to node and some additional libraries could be perfect as take away editor for travelling for example. And yes apple always is a bit ...... when talking about integration...

**Comment by terrychou** [comment]
> Right, later I fixed iCloud too. However, all other cloud services as I tested (OneDrive, Google Drive, Box.net, Dropbox) non of them are supported - i.e. they are all grayed out. iCloud is Mac ecosystem only - I guess nobody uses iCloud outside apple devices.

To link directories from a third-party app, it requires the app to explicitly implement a specific support. Which, I guess, is what the most of apps expected by you lack.

**Comment by terrychou** [comment]
Glad to know that `iVim` helps and you like it, thank you.

Right now, I am busy working on adding native version control support to `iVim`. Are you interested in trying or testing it before its release? If so, please leave me an email address so that I can send you `TestFlight` invitations when it is ready for testing. :)

**Comment by f1se4** [comment]
Of course! sergi.garcia.munoz@gmail.com

**Comment by terrychou** [comment]
@f1se4 I just have pushed the first build of the native-version-control `iVim` to `TestFlight` and you should receive the invitation soon. It is more difficult than I expected, so sorry for the waiting.
