### ISSUE TITLE
Feature Request: Touchpad/Mouse Scrolling

### ISSUE THREAD

**Issue by ahayman** [terrychou/iVim#203]
Double finger scrolling on the screen works great to scroll text.  It would be nice if you could do the same thing with a touchpad (and mouse, which I haven’t tried).  I’ve got a Magic Keyboard and frequently use it to try to scroll.  

Thanks!  iVim is a great app; I use it a lot.

(I’m not sure if posting an Issue is the right way to request feature. If not, let me know where and I’ll post accordingly)

**Comment by terrychou** [comment]
Thanks for the suggestion. I will consider adding better external mouse (touchpad) support into `iVim`.

(Yes, any problem or suggestion is welcomed to post as issues here. And I see you got a thumb up here :))

**Comment by terrychou** [comment]
The trackpad scrolling support has been implemented and will be available in the next update. I think you will like it :).

**Comment by ahayman** [comment]
That's great news!  I look forward to the update!

**Comment by GregoryShields** [comment]
I'm running iVim on an iPad Pro. Neither single nor double finger scrolling work when I pull down, though scrolling does work when I pull upward. When I pull downward, nothing happens other than an error message on the status line that says, "E21: Cannot make changes, 'modifiable' is off." for read-only files or "Already at newest change" for editable files.

Any idea why this might be happening? Is this some kind of "pull to save" feature?
