### ISSUE TITLE
How to tell iVim about bold/italic font files?

### ISSUE THREAD

**Issue by anjiro** [terrychou/iVim#207]
The fonts that come with iVim seem to have bold and italic formatting built-in. But when I add external fonts that use separate files (e.g., anything from https://github.com/powerline/fonts), iVim doesn’t seem to automatically use the bold or italic versions alongside the regular. How can I get it to work?

**Comment by terrychou** [comment]
`iVim` only reads one font file at one time, you need to include all the fonts of the same family into one file (e.g. pack them into a .ttc file).

**Comment by terrychou** [comment]
Related options have been available from the new fonts management module, since version 2.45.
