### ISSUE TITLE
Crash after using settings for iVim

### ISSUE THREAD

**Issue by mac3uck** [terrychou/iVim#208]
Hello,

I found a weird behaviour of iVim:
Whenever I go to the iPadOS seetings for iVim and then (~~even without changing something~~)* switch to the setting of another app, the settings app crashes. After that, when starting iVim, it only flashes once and disappears. In the “open apps view” (exposé) I still see iVim, but as I select it, it flashes again back to the home screen.

I tried the `-u None`, closed all apps, restarting the iPad, etc. The only things that helps is to un- and reinstall the app. Even with a reinstallation and a restart of the iPad its behaviour is reproduceable everytime.

I got the latest iVim, latest iPadOS on an iPad mini 5th gen, external keys.

If that helps to get rid of another bug, iVim will get even better as it already is!

Cheers - André

*) edit:
Only if I deactivate the “font ligatures” iVim itself is not working anymore. Nevertheless the iPadOS settings crashes randomly, if switch between iVim and other app settings!?

**Comment by terrychou** [comment]
By "latest iPadOS", do you mean 14 or 15?

**Comment by mac3uck** [comment]
Oh, sry. By latest I meant official, so: 14.6

**Comment by terrychou** [comment]
I just had the time looking into this issue.

In my testings, the settings-app-crashing problem doesn't only happen to `iVim`. Some other apps' settings crash Settings.app too. Therefore, it probably is some bug with the system.

However, the font-ligatures problem is real. And it has been fixed and will be available in the next update.
