### ISSUE TITLE
Feature request: option to show iOS status bar

### ISSUE THREAD

**Issue by anjiro** [terrychou/iVim#209]
Sometimes I’d like to be able to see the clock while I work; can we have an option to show the status bar?

**Comment by kkebo** [comment]
How about using Vim plugins like these?

- https://github.com/enricobacis/vim-airline-clock
- https://github.com/mopp/sky-color-clock.vim

**Comment by anjiro** [comment]
I'm using the first, but also miss things like battery percentage and signal strength.

**Comment by terrychou** [comment]
This has been added since version 2.51
