### ISSUE TITLE
Extended keyboard covers iOS11 Files picker

### ISSUE THREAD

**Issue by goerz** [terrychou/iVim#21]
When opening the Files document picker with `:idocuments` while the extended keyboard is active, the keyboard line covers the bottom of the picker (where the "Browse" and "Recent" tabs are), see screenshot below:

![img_0119](https://user-images.githubusercontent.com/112306/31258733-5e3f04b6-aa0f-11e7-9837-9f7286369757.PNG)

This makes it impossible to navigate the documents picker.

**Comment by terrychou** [comment]
It's been solved in the coming version.

**Comment by terrychou** [comment]
Fixed in version 1.20
