### ISSUE TITLE
Feature request: tell :ipreview what kind of file it is

### ISSUE THREAD

**Issue by anjiro** [terrychou/iVim#211]
It would be nice to be able to specify a file type for `:ipreview`; for example, I have `.wiki` files that are really Markdown. Something like `:ipreview -f md [path]`.

**Comment by terrychou** [comment]
Thanks for the suggestion! Option "-e or --extension" has been added for this. It will be available in the next update.

**Comment by anjiro** [comment]
Cool, thanks!
