### ISSUE TITLE
iPadOS 15 will go back to the home screen after I open any file with iVim from another app (e.g. Files app)

### ISSUE THREAD

**Issue by kkebo** [terrychou/iVim#212]
## Description

 iPadOS 15 will go back to the home screen unexpectedly after I open any file with iVim from another app (e.g. Files app).

This issue can't be reproduced in iPadOS 14.7.1.

Video: <video src="https://user-images.githubusercontent.com/601636/129755089-5bbf51c6-488e-4133-8b71-ae6363bcb4f3.mov">

## Environment

- iVim 2.31 (App Store)
- iPadOS 15 Developer Beta 5 (12.9-inch iPad Pro 5th generation)

## Steps to reproduce

1. Open Files app
2. Select any file and open the share sheet
3. Tap iVim on the share sheet

## Expected behavior

iVim will launch and the file I selected will be opened in iVim.

## Actual behavior

Although iVim will launch and the file I selected will be opened in iVim, iVim will be closed instantly.

**Comment by terrychou** [comment]
Thanks for reporting!

It turned out to have something to do with the subtle change of scene activation in iPadOS 15. It's been fixed and will be available in the next update.

**Comment by kkebo** [comment]
iVIm 2.41 has been released. I've confirmed that it fixed this issue. Thank you for quick fix!
