### ISSUE TITLE
Terminal is one key behind

### ISSUE THREAD

**Issue by b-** [terrychou/iVim#213]
If I run `:terminal` my key input is always one key ahead of what's happening on screen. By this I mean, if I type `exit<Enter>` the window doesn't press `<Enter>` unless I press any other key after. 

To be clear, it's not just Enter (or Return, rather?) but also any other key at all — as I type `exit<Enter>` each letter only shows up after I type the _next_ one; the `t` isn't there until I press `<Enter>` in the first place.

I'm using `iVim 2.40(5)` according to `:version` running on Developer beta iOS 15.0 (19A5337a)

**Comment by terrychou** [comment]
Although I could not test it on a device since I don't have one with iOS 15 beta installed, I tried to re-produce it in the simulator but failed. 

Anyone else has a iOS 15 beta device? Please tell us whether this happens to you too?

**Comment by b-** [comment]
Hm, it was a weird fluke. It's not doing it now. Closing the issue… I'll comment if it happens again.
