### ISSUE TITLE
ios external keyboard and key repeat

### ISSUE THREAD

**Issue by georgebellos** [terrychou/iVim#214]
I have enabled the key repeat in ios accessibility settings for my external keyboard and until 2 versions ago(current 2.42) everything was working great but now it has a weird behavior , When i press the same key is does repeat itself but the cursor vanishes, only when i press the enter key the key repeats itself normaly and the cursor follows normaly.

**Comment by terrychou** [comment]
Thanks for reporting! 

It turned out caused by an unnoticed trivial change in the code. I've fixed it and it will be available in the next update.
