### ISSUE TITLE
[iOS/iPadOS 15] Hide QuickType bar

### ISSUE THREAD

**Issue by kkebo** [terrychou/iVim#216]
In iOS/iPadOS 14.x and earlier, the QuickType bar has been hidden, but in iOS/iPadOS 15, it now appears.

![41F69B64-C850-4999-8970-36F828264C2A](https://user-images.githubusercontent.com/601636/135764572-e82c3d85-ea12-48bf-a84e-fcbe292c07e3.png)

According to [the release notes](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-15-release-notes),

> In iOS 14 and iPadOS 14 and earlier, when autocorrectionType is set to UITextAutocorrectionTypeNo, the QuickType bar is disabled. For apps linked against iOS 15 and iPadOS 15 or later, the QuickType bar is enabled and shows spellchecking candidates. If the new behavior isn’t desirable for your use case, set spellCheckingType to UITextSpellCheckingTypeNo to hide the QuickType bar. (68874861)

So, I think it is required to add `spellCheckingType = .no` similar to [this line](https://github.com/terrychou/iVim/blob/d09cbb5f47e9088bbbcc32bb2f43834f4a0cf880/iVim/VimViewController.swift#L254).

**Comment by terrychou** [comment]
Thanks for this hint! I've added this to disable the QuickType bar in i(Pad)OS 15 and it is included in the next update.

Actually, it would be better to support the QuickType. But it requires a better conformation to the protocol UITextInput which has poor documentation or example code. I may give it a try when I have time. (#215)

**Comment by kkebo** [comment]
This issue seems resolved in iVim 2.43 (7).

**Comment by kflu** [comment]
> Thanks for this hint! I've added this to disable the QuickType bar in i(Pad)OS 15 and it is included in the next update.
> 
> Actually, it would be better to support the QuickType. But it requires a better conformation to the protocol UITextInput which has poor documentation or example code. I may give it a try when I have time. (#215)

Yes quick type is very helpful as I finger type a lot. Would appreciate if you support this.
