### ISSUE TITLE
iexdir add not working

### ISSUE THREAD

**Issue by AmaruCoder** [terrychou/iVim#219]
The command `iedir` is no longer working.  I am using iVim 2.43 (7) on an iPad Pro (3rd generation) running iOS 15.02. These are the steps:

1. I issue the command `iexdir add`
2. iVim shows the file browser
3. I pick a folder from iCloud
4. No link is created (checking it with `iedir list`

What am I doing wrong?

**Comment by AmaruCoder** [comment]
If you have the same problem, solve it by following the steps below:

1. Open Files in iOS
2. Navigate to "On My iPad" > "iVim"
3. Remove all the links that are not working
4. Open iVim and issue a `iexdir fix` command
5. Recreate the links using `iexdir add`

To the developer: Thank you for keeping this awesome implementation of Vim on the iPad. I use it all the time.

**Comment by AmaruCoder** [comment]
See solution above.

**Comment by terrychou** [comment]
> If you have the same problem, solve it by following the steps below:
> 
>     1. Open Files in iOS
> 
>     2. Navigate to "On My iPad" > "iVim"
> 
>     3. Remove all the links that are not working
> 
>     4. Open iVim and issue a `iexdir fix` command
> 
>     5. Recreate the links using `iexdir add`
> 
> 
> To the developer: Thank you for keeping this awesome implementation of Vim on the iPad. I use it all the time.

Thanks for the reporting! Glad to know that you have already solved your issue and iVim helps. Let me know if you have any further problem or suggestions.
