### ISSUE TITLE
support autoload files?

### ISSUE THREAD

**Issue by ckanthony** [terrychou/iVim#22]
i tried to install vim-plug https://github.com/junegunn/vim-plug by putting their plug.vim into ~/.vim/autoload/, however, the command of plug are not registered

**Comment by terrychou** [comment]
According to its script, vim-plug requires executable `git` installed to run. Unfortunately, this is not allowed in iOS systems.

**Comment by ckanthony** [comment]
You are right, I am using pathogen and it works well

Anthony
