### ISSUE TITLE
2.46(10) screw up my font and display

### ISSUE THREAD

**Issue by kuochang** [terrychou/iVim#224]
Just opened iVim today and suddenly found my screen is “scrambled” as attached. Please note my iVim worked normal before.
![8DAD3268-40F1-43A4-BC34-DCF7127B85A1](https://user-images.githubusercontent.com/58517668/149120216-27b9b414-9b3d-45d2-bf7d-3562a292f037.png)

After investigating, I found iVim will get back to normal when I remove my one line in my customized font setting as below:
“ifont set 'Anonymice Nerd Font Mono' --size 20 -b 'Anonymous pro' -i 'Anonymous pro'”

But the strange thing is if I do key binding with the above line, it works fine(after type if in normal mode):
“nmap <leader>if :ifont set 'Anonymice Nerd Font Mono' --size 20 -b 'Anonymous pro' -i 'Anonymous pro'<cr>“

iVim is my daily driving and I can’t express how much I love it.:) Please help.

**Comment by terrychou** [comment]
Please paste the output of `:ifont ls` here.

**Comment by kuochang** [comment]
Thanks for the prompt response. The output of “:ifont ls” is as attached.
![F3D628CB-C972-4072-A068-AE11C3CC7E27](https://user-images.githubusercontent.com/58517668/149164466-94091224-8061-448a-8bd3-ab85e4068fcd.jpeg)

**Comment by kuochang** [comment]
Again, the problem is I can’t put the “ifont set 'Anonymice Nerd Font Mono' --size 20 -b 'Anonymous pro' -i 'Anonymous pro'” in .vimrc directly because it caused the scrambled screen. But I can execute it in the ex mode with no problem…

**Comment by terrychou** [comment]
@kuochang I have fixed this. Please leave me an email so that I send you a TestFlight invitation for you to test it.

**Comment by kuochang** [comment]
Great! My email address is “chiangiii@mac.com”. Thank you very much for the prompt response and support!

**Comment by terrychou** [comment]
@kuochang invitation sent.

**Comment by kuochang** [comment]
Thanks! I’ll test it after work. Will let you know soon.

**Comment by kuochang** [comment]
Just tested it and the problem is gone with 2.47(1). Thank you!
