### ISSUE TITLE
IPlug fails to install plugin

### ISSUE THREAD

**Issue by EricEWeir** [terrychou/iVim#235]
Attempting to install a plugin named “vim-help” “iplug add https//:github.com/dahu/vim-help” returns “failed to resolve address for https//: nodename nor servname provided, or not known.” 

What am I not understanding or overlooking?

Thanks

**Comment by EricEWeir** [comment]
iPlug works. If I do “iplug list” I get a list of my installed plugins. 

But when I do “iplug add” and include a URL to a plugin on github, e.g., as above, I get “failed to resolve address for https//: nodename nor servname provided, or not known.”

I installed the same plugin from the same URL in MacVim on my MacBook without a hitch.

**Comment by terrychou** [comment]
If the URL is exactly as you wrote above ("https//:github.com/dahu/vim-help"), then the problem may be its incorrect format (the right one should begin with "https://" rather than "https//:").

**Comment by EricEWeir** [comment]
> On Jun 7, 2022, at 10:34 PM, Terry Chou ***@***.***> wrote:
> 
> If the URL is exactly as you wrote above ("https//:github.com/dahu/vim-help"), then the problem may be its incorrect format (the right one should begin with "https://" rather than "https//:").

Thanks, Terry. Often it’s something simple. At least for we rare non-coders who venture into vim. Thanks for making it possible to stick with it in ios/ipados.

----------------------------------------
Eric Weir
Decatur, GA  USA
***@***.***

"It has all been combustion.”

- W.G.  Sebald
