### ISSUE TITLE
Delete directories?

### ISSUE THREAD

**Issue by EricEWeir** [terrychou/iVim#239]
When I attempt to delete an iVim directory, at least in /.vim, I get “unable to delete directory.” Is there a way?

**Comment by EricEWeir** [comment]
Or, if not delete a directory, how to disable a plugin?

**Comment by sedm0784** [comment]
netrw won't let you delete a directory unless it's completely empty, so you need to delete all its contents first.

If you're comfortable with the command line, it's likely quicker to do this by running an `rm` command via `:term`, which allows you to remove everything in one go. (But if you're *not* already comfortable with the command line, this might not be the best place to start learning it.)

**Comment by EricEWeir** [comment]
My initial move away from Windows, before moving on to MacOS, was Linux. I got pretty comfortable with the terminal there. Didn't think of that option, but was able to delete the directory in the Files app.
