### ISSUE TITLE
Add Copy/Paste buttons to the extra keyboard

### ISSUE THREAD

**Issue by holzschu** [terrychou/iVim#24]
Occasionally, users need to copy/paste things to the system clipboard. While it's always possible using, say "+p and "+y, it's not too easy for the average user. 

It would be possible to add "Copy" and "Paste" buttons to the extra keyboard (the one with Esc, Tab, ...) to allow the user to copy and paste to/from the system clipboard, as in @eminarcissus branch of VimIOS: https://github.com/eminarcissus/VimIOS

**Comment by sedm0784** [comment]
Personally, I'm not in favour of this. I'd prefer the keyboard only contain things of more general use.

If we're looking for new additions, I'd choose separate ctrl and esc keys, or a meta key over this.

I'm also slightly sceptical that "the average user" will ever be *using* iVim. It seems more likely to me that the userbase will always be restricted to Vim enthusiasts (who will already know about registers/clipboard=unnamed/how to set up personalized mappings, etc.)

**Comment by terrychou** [comment]
The real estate of the extra keyboard is really precious. :) If I could get another line of room for more buttons, I will never hesitate to add them for an intuitive use.

Maybe there is a better way to provide extra keys...

**Comment by holzschu** [comment]
I understand your concern with real estate issues on small terminals (such as phones). On larger terminals (like iPads, especially the big ones), there is a lot of space available on the row, and even more space that could be freed because the extra keys are already on the standard keyboard (numbers, brackets...) So maybe the issue is: have different versions of the extra keyboard, depending on terminal size.

**Comment by drbarrett** [comment]
It'd be nice if you could customize the extra key row in your .vimrc either like how the statusbar or the guioptions work. Although then you'd want to have different sets of options if it's a phone or ipad.

At a minimum, a different fixed bar for ipad would be great. There's no need to duplicate the keys that are on the main keyboard now. It seems there are 11 characters that can't be found on the main kbd now.

I changed my default clipboard to unnamed so copy and paste are not important to me, but having a meta and cmd key if ios allows it would be great additions. Bonus points for ` which is a major pain to get to.

Side note, I just now discovered the keyboard mode key acts like a shift key if you hold it, type a number/symbol and release. Either it's new in ios11, or I've been an idiot.

**Comment by sedm0784** [comment]
> Side note, I just now discovered the keyboard mode key acts like a shift key if you hold it, type a number/symbol and release. Either it's new in ios11, or I've been an idiot.

Nope, that's not new. You can also drag from the mode or shift key to another key and then release to access those keys with a single (dragged) touch from a single finger!

**Comment by terrychou** [comment]
Added the extended keyboard customization feature in version 1.38 (:h :isetekbd). Now you can make your own buttons or keys.
