### ISSUE TITLE
Keyboard blocks dialog options on first startup

### ISSUE THREAD

**Issue by ghost** [terrychou/iVim#240]
![image](https://user-images.githubusercontent.com/4300747/177021398-57729834-5b57-4b79-877d-739542984682.png)
I was just barely able to hit the first option and everything worked fine from there, I'm unsure what I picked however. 

I keep purchasing disabled until needed for my protection. 

iPhone 6s

**Comment by terrychou** [comment]
Yes, I've encountered this issue too. I will look into it.

**Comment by terrychou** [comment]
A fix is included in the new version 2.51, please give it a try.

**Comment by ghost** [comment]
Thanks for the fix, closing.
