### ISSUE TITLE
Pull to save?

### ISSUE THREAD

**Issue by GregoryShields** [terrychou/iVim#241]
I'm running iVim on an iPad Pro. Neither single- nor double-finger scrolling work when I touch the screen and pull downward, though scrolling does work when I pull upward. When I pull downward, nothing happens other than an error message on the status line that says, "E21: Cannot make changes, 'modifiable' is off." for read-only files or "Already at newest change" for editable files.

Any idea why this might be happening? Is this some kind of "pull to save" feature?

**Comment by terrychou** [comment]
I couldn't re-produce the issue which you are describing here.

Note that scrolling only work when you pan with two fingers and behind the scene, they just invoke `<C-y>` for scrolling downwards. According to your description, the cause may probably be that you have mapped `<C-y>` to redo.

**Comment by GregoryShields** [comment]
As soon as I read your comment I was slapping my own forehead, because I KNEW you were right! Well, except that I can also scroll with one finger.

Thank you!

**Comment by terrychou** [comment]
> except that I can also scroll with one finger

Yes, you are right. This was a bug and has been fixed. It will be available in next update.
