### ISSUE TITLE
Text search utilities that work in iVim

### ISSUE THREAD

**Issue by EricEWeir** [terrychou/iVim#249]
Looking for an enhanced text search utility that will work with iVim given the sandboxing of iOS/iPadOS apps. ripgrep has been recommended. Does it rely on external resources?

**Comment by sedm0784** [comment]
To use `ripgrep`, I believe you'd need it to be added as an [External Command](https://github.com/terrychou/iVim/wiki/External-Commands).

Apologies if this is a stupid question, but have you considered using [`:vimgrep`](https://vimhelp.org/quickfix.txt.html#%3Avimgrep)? It works well for me. I think [`:grep`](https://vimhelp.org/quickfix.txt.html#%3Agrep) should work too, as `grep` is included in iVim, but it's not working for me right now (could be something to do with my config).

**Comment by EricEWeir** [comment]
Thanks for your response. I suspect `ripgrep` does rely on external resources. I’m not familiar with external commands in iVim. Need to check them out.

`ripgrep` was recommended to me, but it may be overkill for my needs. Likely I’m going to be doing searches on a max of 1000 to a few 1000 files. In lieu of a better tool that can be used with iOSs sandboxing of apps I have considered `grep`. Quite possibly it would be sufficient for my needs. I’ll check out `vimgrep`.

Thanks again.
