### ISSUE TITLE
Some external keyboard events are not sent to the app

### ISSUE THREAD

**Issue by holzschu** [terrychou/iVim#25]
The new external keyboard support is great. It make iVim really easier to use.

However, I found that some events are not forwarded to the app. `<D-R>` is sent, and triggers the nmap associated, but `<D-V>` is not sent (it never arrives into input_special_name and input_special_key). 

As far as I can tell, the missing keys are: `<D-V>`, `<D-C>`, `<D-X>` and `<D-Z>`

**Comment by sedm0784** [comment]
Markdown has eaten some of your keystrokes. (I'm guessing ones surrounded by angle brackets.) Surround them with backticks to stop this! e.g. \`&lt;cr>\`

**Comment by holzschu** [comment]
Thanks, I updated the issue.

**Comment by terrychou** [comment]
Those chords are reserved by the iOS system. For example, `D-C` is for `copy`. And they cannot be overridden in the way iVim is using. I will try to add them with workarounds.

**Comment by holzschu** [comment]
Yes, that would be really cool. @eminarcissus managed to do it in his port of Vim (https://github.com/eminarcissus/VimIOS ), although I don't understand how he did it (the differences with this port appear to be subtle).

**Comment by holzschu** [comment]
I found it; the solution is through `override func canPerformAction(_ action: Selector, withSender sender: Any?) -> Bool`. It can do copy, paste and cut (`<D-c>`, `<D-v>` and `<D-x>`).

I am still missing a way to access `<D-z>`.

**Comment by terrychou** [comment]
Yes, but it would be better to override methods such as copy:, cut:.
the coming version will include `<D-c>`, `<D-x>`, `<D-v>` and `<D-a>`.
and `<D-z>` is probably reserved by system for the undo mechanism, we'd better leave it alone like `<D-h>` and `<D-.>`. 

Hey, would you like test iVim via TestFlight? Please give me your email if you would.

**Comment by holzschu** [comment]
That's very nice of you, but I have my own fork (where I'm implementing commands inside iVim). If you just push your changes, I'll pull from upstream.

**Comment by terrychou** [comment]
Solved in commit dc51291aa64e76f98179bde90c1c6815178e059d
