### ISSUE TITLE
:echo system('uniq', ["a", "a", "b"]) —> crash

### ISSUE THREAD

**Issue by bwhelm** [terrychou/iVim#265]
The following leads to a hang and eventual crash: `:echo system('uniq', ["a", "a", "b"])`.

This is with the most recent version of iVim:

> VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 15 2023 11:24:46)
> iVim 2.53(5)
> Included patches: 1-2110

(The above works on Mac and on a-Shell.app in iOS.)

**Comment by terrychou** [comment]
Thanks for reporting! 

It's been fixed and will be available in the next update.

**Comment by bwhelm** [comment]
Testing with new version (2.54(4)), and it's working as expected. Thanks!
