### ISSUE TITLE
:idoc not identifying tagged folders

### ISSUE THREAD

**Issue by bwhelm** [terrychou/iVim#27]
In Files.app I have some files and some folders marked with tags, and I can successfully access them through the Browse panel.
In iVim, `:idoc` allows browsing of files much like in Files.app. However, selecting a tag in the Browse panel will display only a list of files with that tag, and will not display any folders that have that tag.

**Comment by terrychou** [comment]
Added "folder" type to the document picker. Now it works for most apps in Browse. Certain app still no, which I think might have something to do with its own implementation for Files support.
