### ISSUE TITLE
<CapsLock>[arrow] not registering when <CapsLock> mapped to <Ctrl>

### ISSUE THREAD

**Issue by bwhelm** [terrychou/iVim#30]
`<Ctrl>`[arrow] mappings normally work fine. However, when `<CapsLock>` is mapped to `<Ctrl>`, the corresponding `<CapsLock>`[arrow] mappings are not registered.

**Comment by terrychou** [comment]
Which version are you using? They are working for me.

**Comment by bwhelm** [comment]
Having restarted my iPad, I’m no longer seeing this. Sorry for the noise.
