### ISSUE TITLE
General questions on usage/configuration

### ISSUE THREAD

**Issue by mchalkley** [terrychou/iVim#37]
Sorry for the intrusion in this fashion, but I'm not sure what the best way to ask general support questions is.  If this isn't appropriate, I'd really appreciate knowing the right approach.

Is there a way to add key mappings to iVim?  If so, what would be the correct way to map something like 
`nnoremap <Ctrl-t> i<C-R>=strftime('%Y-%m-%d %H:%M:%S')<CR><Tab>` in iOS?  I use this "Windows-version of a timestamp" key mapping a lot in editing logs, data files for research projects, etc.

**Comment by terrychou** [comment]
I edited your message because github had eaten some characters of your command.

And I think what you are looking for is `nnoremap <C-t> i<C-r>=strftime('%Y-%m-%d %H:%M:%S')<CR><Tab>`

**Comment by mchalkley** [comment]
Thank you. I’m not sure how I set this in iVim, though. Do I create a vimrc file in the iVim documents folder?

**Comment by terrychou** [comment]
Yes, you can put it in your config file like `.vimrc` in the `Documents` (it is the default `HOME` in iVim) folder.

**Comment by mchalkley** [comment]
Thank you again!

Mark
