### ISSUE TITLE
vimrc and ctrl-A (to select all)

### ISSUE THREAD

**Issue by IRigoutsos** [terrychou/iVim#39]
Greetings.  Congratulations on porting to the iOS vim, which I consider the best Editor out there! 😄 

I began using vimrc to set up my ivim and noticed what appears to be a problem.  Specifically, when I make ivim read the vimrc, I cannot use ctrl-A to select all the text in the file that is being edited. I use ctrl-A together with ctrl-C to copy text from ivim into other iOS apps.  However, if I do not read vimrc when starting ivim, then ctrl-A works just fine.  

Is this is a ‘bug’ or am I overlooking something?

Thanks!

**Comment by terrychou** [comment]
By default, what `ctrl-a` does is not to "select all the text" in vim. So I suspect that you are using a plugin to do that. It is hard to tell what is wrong without seeing you configurations.

If you are looking for a way to share text from iVim to other apps, seeing ":help ios-share" may help.

**Comment by IRigoutsos** [comment]
Thank you for the speedy reply.  

- if the “Arguments” line in Settings is empty then “ctrl-A” selects all the text
- on the other hand if the “Arguments” line is set to “-u vimrc” then “ctrl-A” does not work (it puts ivim into ‘input mode’).  

My vimrc is really straightforward (see below) and this is why I am puzzled by this behavior.  BTW, I use Apple Smart Keyboard with the more recent ipad pro (summer 2017).

Any and all suggestions will be welcome.

ps.  I am familiar with :ishare but if I am not mistaken it does not work if the receiving app does not accept .txt files.  E.g. I can send text I just composed in ivim to Word - but I can copy and paste it if I do not add “-u vimrc” in the Arguments line.

———————

ifont 1 15
syntax on
set autowrite
set history=100
set spell
set showmode
set cursorline
set autoindent
set incsearch
set hlsearch
set shiftwidth=1
set showmatch
set wrapscan

**Comment by IRigoutsos** [comment]
(one more perhaps relevant bit of information)

I just noticed that if I remove “-u vimrc” from Arguments, then open a file in ivim and run “:so vimrc” I get all of the settings of the vimrc file (see above) **and** ctrl-A does select all text now.  So it appears that something is done differently when “-u vimrc” is present.

**Comment by terrychou** [comment]
If you just want to load the configurations in your file, try and rename it from `vimrc` to `.vimrc` instead of loading it from the `-u` option. In that case, iVim will load your `.vimrc` automatically. Using the `-u` option may put vim into 'compatible' mode, which might be the cause of the problem.

**Comment by sedm0784** [comment]
As an aside, if you want to copy all the text of a buffer into the clipboard, an alternative method that doesn't require any mappings is to use the command:

    :%y+

**Comment by IRigoutsos** [comment]
Great -- my thanks to everyone for your helpful feedback!
