### ISSUE TITLE
copy paste and iOS 11

### ISSUE THREAD

**Issue by cormullion** [terrychou/iVim#4]
iVIm is great! Just wondering whether it will work OK in IOS 11?

Also, is there a way to copy text to and from iVim and other apps via the clipboard?

**Comment by terrychou** [comment]
Although it has not been actually tested yet, I think iVim will work fine on iOS 11 as long as there is no big changes in APIs. 

The interaction with the system clipboard part has not been implemented yet, I will give it a try.
