### ISSUE TITLE
External keyboard loses half its function when software keyboard is hidden

### ISSUE THREAD

**Issue by BlueDrink9** [terrychou/iVim#44]
I'm using a 3rd party software keyboard. When I hide it, only lower-case letter input from my external keyboard will be registered by iVim. `i`,`w` , etc and `esc` are fine. `Backspace`, `;`, `:` and `ABC` are not.
The default Apple keyboard is disabled.
App Store version 1.32, iOS 9.3.3.

**Comment by BlueDrink9** [comment]
Sorry for the terse explanation.

When the software keyboard is shown, all buttons work as expected.

`caps lock` is mapped to `esc`. I can't remember if it worked but I think it didn't.

Disabled as in, in `General/keyboard`, only my 3rd party keyboard is enabled.

**Comment by BlueDrink9** [comment]
I haven't tried re-creating with the apple keyboard. I'll do that now

**Comment by BlueDrink9** [comment]
The apple keyboard autohides, and can't be displayed while the keyboard is connected. However it works fine in this situation. When this keyboard is not in the available keyboards, the problem occurs. Some 3rd party keyboards will hide themselves, and the problem won't occur until the screen is held, at which point it reoccurs.
Seems like holding to hide keyboard, when an external one is connected, disables most input.

**Comment by terrychou** [comment]
Because of the limitation of the APIs, the `caps lock` mapping is implemented in a very restricted way. Except for the default English keyboard, other keyboards are not well supported. 

Your problem is probably caused by this. So you can disable the `caps lock` mapping to see whether it works or not.

**Comment by BlueDrink9** [comment]
Will do. It would be a shame if that were the problem, it's bloody brilliant having my pinky do what it expects to.

**Comment by BlueDrink9** [comment]
Also to clarify, `caps lock` does indeed send `esc` (mapped to `backspace` in vim). This is even with non-default keyboards.

**Comment by terrychou** [comment]
Yes, but the most annoying part in the `caps lock` mapping implementation is that the uppercase letters need special handling. Which is the main reason why non-standard keyboards would not work.

**Comment by BlueDrink9** [comment]
Aah, true. That includes `backspace`, `;` and `:`?

**Comment by terrychou** [comment]
You can check out the implementation of the external keyboard in file https://github.com/terrychou/iVim/blob/master/iVim/VimViewController%2BExternalKeyboard.swift

**Comment by BlueDrink9** [comment]
Sorry, just got back into using this. Can confirm that switching back to no caps mapping doesn't solve the problem.
