### ISSUE TITLE
support Working Copy integration

### ISSUE THREAD

**Issue by vvuk** [terrychou/iVim#45]
Working Copy is a (fantastic) git client for iOS.  The combination of solid git + iVim would make for a great local development environment.

Working Copy supports two approaches:
- WebDAV support.  It can spin up a WebDAV server for a repository;
- or URL-based x-callback-url commands: https://workingcopyapp.com/url-schemes.html

The latter is more powerful (and supports a full suite of git commands, but also includes simple read file/write file/list files), the former might be more generic.

It would be great if iVim supported one of these approaches -- integrating a simple webdav client should make it possible to tie things in to netrw.

**Comment by terrychou** [comment]
The branch https://github.com/terrychou/iVim/tree/openurl adds x-callback-url support into iVim. While it is still under testing, you can check it out and run it via Xcode. Type ":h ios-open-url" to see the details.

Any suggestions are welcome.

**Comment by MarkVillacampa** [comment]
Since you can already open a Working Copy directory in iVim, what would this funcionality add?

**Comment by mikesale** [comment]
I use Working Copy with iVIm daily, the "Open in" sharesheet is great! Would prefer to see upgrade of vim itself

**Comment by idvorkin** [comment]
@mikesale When you open in iVIM how do you get the changes back to working copy?

**Comment by bilal-khan** [comment]
@idvorkin add working copy as a file manager in the Files app and then open in place using `:idocuments` in ivim
