### ISSUE TITLE
Feature Request: Autocomplete in extended keyboard

### ISSUE THREAD

**Issue by bobpepin** [terrychou/iVim#48]
Hi,
it would make programming on the iPad without a keyboard much faster if the top n autocomplete options  could be displayed and selectable in the line above the keyboard, where the extended keyboard buttons are right now. Similar to what one gets for natural language for example when writing text messages. Also, with iOS 11 most special characters are directly accessible from the on-screen keyboard, making most of the extended keyboard buttons somewhat redundant and possibly freeing up space.

I have no idea how hard this would be to implement, just wanted to write down the idea somewhere.

Best,
Bob

**Comment by terrychou** [comment]
Since the autocompletion in vim goes in its own way: providing popup menu for the candidates, this seems not so necessary.
