### ISSUE TITLE
Amazing!

### ISSUE THREAD

**Issue by sedm0784** [terrychou/iVim#5]
This is not actually an issue, but I can't find any other way of contacting you on your github profile.

This port is awesome. This fixes all the issues I had with the Applidium port that made it unusable for me.

Thanks!

**Comment by bwhelm** [comment]
Agreed -- it is awesome. Thanks very much for your hard work!

**Comment by terrychou** [comment]
Glad to know that you people like it! And you are welcome. Actually, your feedbacks often inspire me. Just keep them coming :)
