### ISSUE TITLE
Possible to add colorschemes?

### ISSUE THREAD

**Issue by mtwebb** [terrychou/iVim#50]
Is it possible to add custom colorschemes to iVim?

**Comment by mtwebb** [comment]
I tried adding one to the HOME directory and inside a colors subdirectory, but no luck so far.

**Comment by mtwebb** [comment]
Ahh, got it.  I needed to create the .vim subdir in the iVim HOME dir.  The native Files app does not allow files/dirs that start with period, but the very useful openterm app has not such restrictions and worked like a charm.

**Comment by RunningUtes** [comment]
I am using iVim and can’t seem to get fonts, plugins, or colorschemes installed. It sounds like you were able to get it working on your system. Could you outline the steps you took?

**Comment by terrychou** [comment]
The key to installing plugins, colorschemes or other configurations, is to know the differences of filesystems of iVim. See ":help ios-file-system".

Fonts are handled in its own way under iVim. See ":help ios-font-management".
