### ISSUE TITLE
Suggest Extended Keyboard default to hidden when hardware keyboard is attached.

### ISSUE THREAD

**Issue by mtwebb** [terrychou/iVim#51]
Extended Keyboard is great paired with the software keyboard, but I find I rarely use it when I have hardware keyboard attached (especially since caps lock can be remapped). I usually end up starting every session with the long press to dismiss the extended keyboard.    

What do you think about defaulting the keyboard extension to off when an external keyboard is attached?

**Comment by terrychou** [comment]
Actually, I thought about this function when I was implementing the external keyboard part. But I haven't been able to figure out how to detect the events when a hardware keyboard is connected to the device. (Anyone who has the solution please be generous to share?)

As an alternative, I will add a settings option to iVim that will hide the extended keyboard by default.

**Comment by mtwebb** [comment]
This thread discusses some options: https://stackoverflow.com/questions/31991873/how-to-reliably-detect-if-an-external-keyboard-is-connected-on-ios-9
It’s iOS 9, but comments have some updates for iOS 11.  

That said, a toggle in the settings app sounds good too.

**Comment by terrychou** [comment]
Added in version 1.38 (:h ios-settings)

**Comment by mtwebb** [comment]
Cheers Terry.  Works like a charm.

**Comment by idvorkin** [comment]
This no longer seems to work. With my external keyboard when I open iVim the software keyboard still pops up.   It also pop up, when I re-focus into iVim. How can I help debug the issue?

**Comment by sedm0784** [comment]
@idvorkin Not sure if you may have misread the above: this issue only concerns the extra row that iVim adds to the software keyboard rather than the entire keyboard, and the fix was to add an option to the settings to hide the addition by default.

Unless I'm misunderstanding it, I think your comment is about a different issue?

**Comment by idvorkin** [comment]
@sedm0784 - right you are thanks! Original comment erased.
