### ISSUE TITLE
Create bookmark for directories opened in-place

### ISSUE THREAD

**Issue by MarkVillacampa** [terrychou/iVim#52]
When opening a directory via the document picker, iVim could create an alias file in disk using the following method:

https://developer.apple.com/documentation/foundation/nsurl/1408532-writebookmarkdata

This way, iVim could navigate to a previously opened directory without having to go through the document picker again.

**Comment by terrychou** [comment]
Do you mean keep the bookmark between different iVim sessions? Because there is actually bookmark data for each open-in-place item within one session.

Since there may be editings done by other apps between two iVim sessions, it would be better to pick the items again.

**Comment by MarkVillacampa** [comment]
Yes that's what I mean. Textastic does this with any externally picked directories, keeping a bookmark in the sidebar between launches.

You're right other apps could modify the files in between sessions, but other apps could *also* modify the files whiles iVim is opened.

I think this feature wold be very useful for many people who always work on the same projects and dont want to pick the directory after each iVim launch.

**Comment by terrychou** [comment]
Added solution for this in version 1.38 (:h ivim-old-documents)

**Comment by MarkVillacampa** [comment]
Awesome! Thank you!
