### ISSUE TITLE
User Font not supporting Ligatures

### ISSUE THREAD

**Issue by mikesale** [terrychou/iVim#53]
When I installed Fira Code ttf and otf fonts ligatures are not displaying when the font is selected via .vimrc nor via :ifont selection.

**Comment by terrychou** [comment]
The "ligature" feature introduced on Fira Code needs special handling. Right now it is not supported in iVim. I will give it a look.

**Comment by mikesale** [comment]
Thank you! If there's anything I can do to help with research, testing, etc. I am happy to help.

**Comment by terrychou** [comment]
It is not compatible with the character rendering in iVim right now. So I have to put it on the todo list with lower priority. It will be added when the timing is right.

**Comment by mikesale** [comment]
Any update on this working soon?

**Comment by terrychou** [comment]
This feature is now available in version 2.16.
