### ISSUE TITLE
User Fonts Install Properly but Can’t Be Selected

### ISSUE THREAD

**Issue by danyadsmith** [terrychou/iVim#54]
I have attempted to install and use the following fonts in iVim:

* [Camino Code](https://www.myfonts.com/fonts/jan-fromm/camingo-code/)
* [Pragmata Pro Mono](https://www.fsd.it/shop/fonts/pragmatapro/)
* [Pitch](https://klim.co.nz/retail-fonts/pitch/)

The first one (Camino Code) works as expected. The other two (I have tried the versions with and without ligatures) install properly and are listed when I call the `:ifont` command but when I try to switch to them nothing happens.

I have also tried setting the fonts in the .vimrc file but those changes will accept the font height I select :h17 but will use CamingoCode instead of the option I attempted to set.

Can you give me some guidance to troubleshoot this further? Pragmata Pro is a TrueType font. Pitch is an .otf font. According to `:help` both file types are supported. I can use these fonts in Vim on the terminal and nvim-qt on the desktop.

I have attempted to uninstall all fonts and only install one (without CamingoCode) to see if that made a difference. It didn’t.

p.s. Thank you for creating iVim. It is the best port of Vim I have found for iOS and I use it every day. I’m starting to become “one of those Vim people” in part because this app exists.

**Comment by terrychou** [comment]
I have tried all the three fonts: Camingo Code (Regular, ttf), Pragmata Pro (Regular, ttf) and Pitch (Regular, otf, test version from the official site). And they all seem working fine here.

What do you mean by "nothing happens"? What does `:ifont` list look like after your attempt to switch to a font with failure? Where is the `*` indicator after the failure? Was it indicating the failed font?

How do you use `:ifont` to switch fonts? using the index or name? It would be better if you can provide the related lines in `.vimrc`.

Thanks for the p.s., I am very glad to hear that you like iVim and it helps.

**Comment by danyadsmith** [comment]
@terrychou What I mean by “nothing happens” is that the asterisk that identifies the selected font does not change, the font on screen does not change, and no error message is displayed. To make the situation a little clearer, I have created [a video that walks through the issue](https://drive.google.com/open?id=1oKDGGjjOhHogBknC_tAThJ4HDyfI6txn). I hope it helps to illustrate the problem. It is stored on my Google Drive with a shareable link. In case you have trouble accessing it, this is how I am using the `ifont` command: 

First off, this is what shows up in the Available Fonts list when I enter `:ifont`:

     1     s    SourceCodePro-Regular
     2     s    Courier
     3     s    CourierNewPSMT
     4     s    Menlo-Regular
     *5   u    CamingoCodeRegular      17.0
     6     u    Pitch
     7     u    PragmataProMono
     8     u    PragmataProMonoLigatures

I have tried the following commands to switch fonts using full names, partial names, and the underscore to change only the font size. These only work when selecting fonts with ID 1-5:

`:ifont 1 16` - Changes the selected font to SourceCodePro-Regular at height of 16
`:ifont Camingo 20` - Using a partial font name works. Changes the selected font to CamingoCode
`:ifont _ 30` - Keeps the selected font but changes the size
`:ifont PragmaProMono 16` - Does not change the font
`:ifont 6 20` - Does not change the font

**Comment by terrychou** [comment]
Could you share the fonts with problem? Because it looks wrong in your video but I don't see that with the ones I have, I need to test them on my device to see whether it is the problem with the fonts or not.

**Comment by danyadsmith** [comment]
I would be violating the license agreement by sharing them. I will try to reproduce the issue with some open source fonts this week and get back with you.

**Comment by terrychou** [comment]
By "share", I meant that maybe you could "provide" the fonts in question for the testing purpose only. I never mean to have or use them myself. To avoid this technical problem becoming a legal one, I think I should stop here. Thanks for your feedback.
