### ISSUE TITLE
How to access settings? 

### ISSUE THREAD

**Issue by idvorkin** [terrychou/iVim#59]
*Apologies if this is obvious, I could not find it on the README, or in :help ios*

How do I access the settings for iVim? Is there a UX? Is there a list of the settings and how to use them?

**Comment by terrychou** [comment]
iVim specific settings are put in the system Settings.app, search for "iVim" to reach it. Type `:h ios-settings` to see their explanations.

**Comment by idvorkin** [comment]
I don’t follow. Can the settings be changed on device?
Are they build time?

**Comment by terrychou** [comment]
What do you mean by "settings"? It seems that we don't agree on its meaning.

**Comment by idvorkin** [comment]
I'd expect ios specific settings would be something settable  via ```:set ``` or via some menu.

**Comment by terrychou** [comment]
Some settings cannot be put inside iVim. One example is the launch option for iVim, it needs to be set even before iVim starts. 

The principle is that setting options will be added only when unavoidable. And their default behaviors would meet most use cases.

**Comment by sedm0784** [comment]
Just to make it 100% clear, it is possible to change the ios-specific settings on device:

From your home screen, tap on the Settings App:

![photo 13-12-2018 9 12 59 am](https://user-images.githubusercontent.com/139165/49929245-f81f3600-feb9-11e8-8334-59c095c3bf5a.jpg)

Then you can either scroll up to fix the search field, or simply scroll down till you find iVim in the list:

![photo 13-12-2018 9 16 27 am](https://user-images.githubusercontent.com/139165/49929304-1d13a900-feba-11e8-96cc-0ced33e4eb41.jpg)

**Comment by idvorkin** [comment]
Perfect = thanks!
