### ISSUE TITLE
Is it possible to close the on screen keyboard?

### ISSUE THREAD

**Issue by sedm0784** [terrychou/iVim#6]
In the Applidium port, using a two finger drag to scroll would cause iOS's on screen keyboard to close, which, on a phone, was much nicer for reading long segments of text.

This port doesn't seem to do that. Is there another method of closing the soft keyboard, and, if not, is it possible to create one, or reinstate the old behaviour?

**Comment by terrychou** [comment]
iVim does not have specific code to handle this. On an iPad, I think you can hide the keyboard via the key on the right bottom.

**Comment by lifepillar** [comment]
On a phone, go to landscape mode to see the bottom right button to dismiss the keyboard. When the keyboard is closed, you may turn the phone to portrait mode if you want.

Tapping anywhere on the screen will make the keyboard reappear.

**Comment by sedm0784** [comment]
I very rarely use the landscape keyboard (hate the positioning of the extra keys on larger iPhones) so I've somehow never noticed that the keyboard dismiss button is always present.

Just using this key works for me, so as far as I'm concerned, this issue can be closed (I won't close it myself in case you still intend to add a method that doesn't involve rotating the phone).

Thanks!

**Comment by terrychou** [comment]
I will think about it. Then I will close this issue if I don't get anything exciting.:)

**Comment by terrychou** [comment]
Solved in version 1.20
