### ISSUE TITLE
Compatibility with iOS 12

### ISSUE THREAD

**Issue by lifepillar** [terrychou/iVim#60]
I am experiencing issues with iVim under iOS 12 (the app hangs after a few keystrokes). Any chance to release an update any time soon?

**Comment by terrychou** [comment]
Which version are you talking about? The latest version 1.40 is supposed to solve related problems.

**Comment by lifepillar** [comment]
You are right! I was pretty sure I was using the latest version, but today I’ve found an update and now it works.

**Comment by terrychou** [comment]
You can check iVim's version via `:intro` or `:version` at any time.

**Comment by lifepillar** [comment]
Sure, but in the broken version the app would hang after typing `:vers<enter>`.
