### ISSUE TITLE
Bold and italics support

### ISSUE THREAD

**Issue by barmatal** [terrychou/iVim#62]
I’m not sure if this is a bug but I can’t find a way to make it work so maybe someone here can help me.

I copied my vimrc and plugin files and almost everything worked out of the box (this port is AMAZING!) except that the plugin I use for Markdown formatting do not display bold and italic format. I’ve tried installing fonts with regular, bold and italics versions but it doesn’t work (I can select them and make all text bold, or all text italic, but that’s all)

**Comment by terrychou** [comment]
Unfortunately, bold or italic drawing is not supported in iVim currently. However, I don't quite understand the last part you are talking about. Do you mean that it will draw bold or italic font when you apply them all? Can you try and remove all the installed bold or italic versions to see that still work?

**Comment by barmatal** [comment]
Sorry, that was confusing. I meant that I installed “Source Code Pro - Italic” and “Source Code Pro - Bold” from [this link](https://www.fontsquirrel.com/fonts/source-code-pro) to test if iVim would catch them and use them in formatted text automatically, but it didn’t work. What happened is that those two fonts appear in the ifont command, so if you run `:ifont SourceCodePro-Italic` all text displayed in iVim will be in italics (obviously)

**Comment by terrychou** [comment]
This support has been added in version 2.13.

**Comment by kuochang** [comment]
Just updated and thank you for the support!

**Comment by avidiotic** [comment]
@terrychou, is there any documentation on how to use the support?

I have regular, italics, and bold versions of JetBrainsMono installed, but I can only set up one as the `guifont`.

**Comment by terrychou** [comment]
@avidiotic set the `guifont` to the regular one should do. Or, it would be more convenient to use the command `:ifont` to manage fonts in iVim (":h :ifont").

**Comment by avidiotic** [comment]
I tried both `guifont` and `:ifont`. I used my vimrc for reference, where I get italics for comments when I use the preloaded fonts. My uploaded versions of JetBrainsMono show up as three different fonts in the `:ifont` menu. Setting the font to JetBrainsMono-Regular gave me underlined comments (instead of italics).

**Comment by avidiotic** [comment]
Thanks for the response! Setting that and restarting iVim worked.
