### ISSUE TITLE
Not available on the AppStore

### ISSUE THREAD

**Issue by AmaruCoder** [terrychou/iVim#66]
First, thank you for porting Vim to the iPad. I tried to install it, but I get the message “This app is not available in your region.”

**Comment by imaxhung** [comment]
+1
I reset my ipad pro, then missing iVim. 
Can you release a unsigned ipa file？

**Comment by terrychou** [comment]
This happened because the Apple Developer account expired.

It should be OK now.

**Comment by imaxhung** [comment]
Now, available in China app store.

**Comment by AmaruCoder** [comment]
Thank you very much!
