### ISSUE TITLE
[Bug] Open-in via share sheet doesn’t open the document in iVim

### ISSUE THREAD

**Issue by qqquwu** [terrychou/iVim#67]
Hi — just purchased via IAP for the restore feature. Very nice app, glad to support.

I was able to open a few documents via share-sheet Open-in-IVim, but now it doesn’t work after I messed around in iVim with opening some local files , etc.  I’m not sure what broke — but it seems like a bug. Any file that I open-in-iVim (ie, from Working Copy) doesn’t do anything in iVim.

**Comment by qqquwu** [comment]
I think it may be because I loaded my .vimrc but none of the directories referenced (such as swap or backup) and plugins exist in the $HOME/.vim/ folder.  After loading my own .vimrc, I think the open-in-iVim broke.

**Comment by terrychou** [comment]
Would iVim open an empty tab for you, or just nothing happened?

Does this happen when iVim in background (i.e. it did not terminate but just enter background)?

**Comment by terrychou** [comment]
This problem should be fixed in version 1.52, so close it for now.
