### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by sedm0784** [terrychou/iVim#7]
Vim allows many different `colorschemes`, but the software keyboard displayed is currently always a light one.

Ideally, I'd like Vim to auto-adjust the keyboard colour (with [UIKeyboardAppearance](https://developer.apple.com/documentation/uikit/uikeyboardappearance)) based on the `background` setting, but any method of setting the keyboard colour would work for me.

**Comment by terrychou** [comment]
I will give it a consider but with low priority.

**Comment by sedm0784** [comment]
I might have a crack at this myself, actually. (At first, via a new setting in Settings.app rather than the automated version I describe above, which I presume would require changes in Vim's upstream codebase.)

If I do so, would you consider merging a pull request?

**Comment by terrychou** [comment]
Of course, it would be great if you take part to make iVim better.

Just one note, to make the code easy for maintaining, I have been trying best to modify as least code of the original vim as possible. It would be nice if the added function interferes with other parts in the least degree.

**Comment by mtwebb** [comment]
Now that iOS 13 is out, dark mode is an officially supported concept. A keyboard that displayed according to system dark mode would be one way that is separate from the vim codebase.

**Comment by terrychou** [comment]
This is already included in the upcoming update, I will update here when it is available.:)

**Comment by terrychou** [comment]
It (version 1.53) is available in App Store now, go grab it.:)

**Comment by mtwebb** [comment]
Just tested it. Works great. And with the dark mode toggle in control center it’s fast to swap.
