### ISSUE TITLE
Open directories in iOS 13 via idocuments

### ISSUE THREAD

**Issue by markuzzi** [terrychou/iVim#72]
I am not able to open directories using the :idocuments command.
The iOS dialog does not allow to select directories.

Is this a restriction of the new iOS 13? Or am I missing anything?

**Comment by markuzzi** [comment]
Seems to be a feature: [see apple docs](https://developer.apple.com/documentation/uikit/view_controllers/providing_access_to_directories)

**Comment by terrychou** [comment]
a screenshot would be more helpful here.

**Comment by markuzzi** [comment]
Sure, sry. I use the command :idoc which opens the file selector. Directories are not selectable in this dialog:

![IMG_0005](https://user-images.githubusercontent.com/35071904/65028763-df5a1a00-d93c-11e9-90e3-1e2dcdcfff5d.jpeg)

**Comment by markuzzi** [comment]
Hi terry, is there anything else I can support you with?

**Comment by terrychou** [comment]
@markuzzi No, sorry for the delayed reply.

It turns out that the directory opening in iOS 13 needs to be done in another separate UI. This problem has already been fixed. The fix will be available in the upcoming update.

Thanks for help.

**Comment by terrychou** [comment]
The updated version 1.53 is now available in App Store. It adds a new mode `dir` to the command `:idocuments`. To open external directories in iOS 13, use `:idoc dir` to invoke the new UI.
