### ISSUE TITLE
Would you like to test iVim with vim 8 core?

### ISSUE THREAD

**Issue by terrychou** [terrychou/iVim#75]
Hi, everyone, I am trying to upgrade iVim with vim 8 core. Because it would be a big change, much testing is needed before delivering it to App Store. Are you interested? If so, please offer me your email address so that I can send you TestFlight invitation. 

Regards.

**Comment by mtwebb** [comment]
Happy to test. Email sent.

**Comment by terrychou** [comment]
@mtwebb Thanks for help, invitation should be sent.

**Comment by mtwebb** [comment]
so far, so good. I’m not pushing on vim 8 features, but day to day is working well.

**Comment by drbarrett** [comment]
I'm happy to test. email is in my profile.

**Comment by terrychou** [comment]
@drbarrett thanks, invitation should be sent.

**Comment by bradleyjones** [comment]
I'd also be happy to test, email in profile

**Comment by terrychou** [comment]
@bradleyjones thanks, invitation sent.

**Comment by xiaopihai7256** [comment]
here is my email: liuyifeii917@live.com

**Comment by terrychou** [comment]
@xiaopihai7256 thanks, invitation sent.

**Comment by terrychou** [comment]
build 2 has been delivered. 

I cannot reply to the feedbacks via TestFlight. You can also reach me via the email in my profile. Thanks!

**Comment by terrychou** [comment]
I have delivered iVim version 2.00 to App Store. But of course, please go on reporting any problem you find.
