### ISSUE TITLE
Remote Editing via scp

### ISSUE THREAD

**Issue by markuzzi** [terrychou/iVim#77]
Would it be possible to have ssh/scp built in to allow for remote editing (via netrw)?

**Comment by terrychou** [comment]
Yes, it is possible. I will consider it when the timing is right :).

**Comment by terrychou** [comment]
version 2.10 is ready on App Store now. The scp:// protocol should work in netrw now. Check it out.

**Comment by markuzzi** [comment]
Awesome! Thanks very much!

**Comment by videoMonkey** [comment]
Can I see an example of how to do this? Thanks!

**Comment by terrychou** [comment]
@videoMonkey First, you need to enable SSH connection from iVim to your target machine, please refer to this wiki page: https://github.com/terrychou/iVim/wiki/External-Command:-ssh ; Then use a URL as the target filename in your Ex command, example: `:e scp://username@host:filepath`. It will work just like local thanks to `netrw`.

**Comment by videoMonkey** [comment]
Thanks for that answer! I did find the docs but I got confused as to what command to issue to get a remote file. Thanks!

**Comment by videoMonkey** [comment]
Alas, it would seem that the server that I am trying to connect to only allows for password auth, thanks for your help. This is a great trick to have.
