### ISSUE TITLE
Directory-wide searching

### ISSUE THREAD

**Issue by Cedric-Garcia** [terrychou/iVim#78]
I’m struggling to find a way to search through a full directory of text files in vim, have tried the following:

* :grep - Doesn’t seem to work, returns a ‘can not fork’ error
* :fzf- Tried installing the fzf vim plugin (via Pathogen, through which I have successfully installed other plugins), but it seems it relies on an executable, so that’s a no-go
* :ctrlsf - Tried installing this plugin (Pathogen too), but crashes with ‘unknown function CtrlSF#Search’

Has anyone managed to do directory-wide searching through iVim? It seems to be a pretty useful feature in the Vim environment overall and would likely be very useful here.

**Comment by terrychou** [comment]
Have you ever tried `:vimgrep`? (`":h vimgrep"`)

**Comment by Cedric-Garcia** [comment]
Took a bit of fiddling but it worked! Closing.
