### ISSUE TITLE
Feature request: Is Python integrated possible?

### ISSUE THREAD

**Issue by StrayDragon** [terrychou/iVim#79]
Hello, :hand:
I am very grateful to you for developing and maintaining this app. Let me learn and use Vim again. 

However, I tried to install a lot of plugins these days. As you said in the documentation, many exciting plugins are not working due to various restrictions. One of reason is they depend on other scripting languages, like Python and others. Is it possible to integrate them? 

Anyway, iVim has helped me a lot, thanks again!

**Comment by terrychou** [comment]
Glad to hear that you like iVim. 

Yes, it is possible to integrate scripts support, such as python or lua, into iVim. In fact, I have been trying to add external commands support into iVim. But it needs some time since it requires certain low level changes.

**Comment by StrayDragon** [comment]
That's awesome! :smile: 
Thanks for your reply and looking forward to an update to these features.

**Comment by terrychou** [comment]
@StrayDragon the beta will be ready, would you like to try it? If so, please given me an email so that I can send you the TestFlight invitation.

**Comment by StrayDragon** [comment]
@terrychou Wow, very happy to test it, here is my email: straydragonl@foxmail.com

**Comment by StrayDragon** [comment]
@terrychou Thank you, I received your invitation.But my location of Apple id is in China and there are some regional restrictions or policies that make it impossible for me to load this test version. I also try to activate with redeem code, however, it only shows that the TestFlight server is not connected(actually, it works well).

That's too weird, and I could find/install/update `iVim` in App Store(China), but I can't load it in the TestFlight.

Is there a regional option(or related settings) for the distribution of the test invitation? If not, I think I may only accept it in the official version :disappointed:

**Comment by terrychou** [comment]
@StrayDragon no, the situation right now is that I just added your email into the tester group but I haven't uploaded the app to TestFlight yet. You should be notified and able to install it when the app is in position.

**Comment by terrychou** [comment]
@StrayDragon it should be available now. 

I didn't provide the SSL certificate file in this upload, so you may need to obtain it by yourself. Please refer to the environment variable `$SSL_CERT_FILE`. (:echo $SSL_CERT_FILE)

Also, the module `pip` is available, please try it.

**Comment by StrayDragon** [comment]
@terrychou That's great, I have successfully installed it, thank you for adding these feature, I will do some testing and provide feedback as much as possible.

**Comment by terrychou** [comment]
The new update (version 2.10) has been delivered to App Store. Thanks for helping. Please report if there is any further problem.

**Comment by StrayDragon** [comment]
Yes, I already updated `iVim` from App Store, this issues has been solved.
but some not very important bugs which I mentioned in the email will still appear in the latest version of `iVim`.If possible, I will open new issues.
Thanks again 😃
