### ISSUE TITLE
Crash with long global variable names

### ISSUE THREAD

**Issue by bwhelm** [terrychou/iVim#8]
From the command line, enter

     let g:a_very_long_global_variable_name = 1

iVim instantly crashes. Any global variable name with 30 or more characters will make iVim crash.

Note that this is particularly problematic when a global variable name is defined in `.vimrc` or a plugin or any other file `source`d on launch: iVim immediately crashes, leaving the user no choice (as far as I can see) but to delete the iVim app (and so all user files), re-download it, and recreate everything in the .vim folder.

**Comment by terrychou** [comment]
Please do some testings concerning this part.

**Comment by bwhelm** [comment]
Once again I'm testing in the simulator and not on my iPad, but everything seems to work here. Thanks!

**Comment by terrychou** [comment]
Fixed in version 1.10
