### ISSUE TITLE
:isetekbd don't working

### ISSUE THREAD

**Issue by pome-ta** [terrychou/iVim#81]
hi!
I enjoy ivim very much. Thank you for making!

I have iphone11 (iOS13.2.3) and iPad Pro 10.5inch (13.1.2), and the ivim version is 2.00 (3).

`: Isetekbd` is `remove` works, but `append` and `insert` do not work.

The error log is `invalid locations nil`.

I wrote the following on the cmdline:
```
:isetekbd {'operation':'remove', 'locations':[3]}
```
or
```
:isetekbd remove {'locations':[0], 'buttons':[{'locations':[1]}]}
```

Since it was executed safely, I wrote the following and executed it:
```
:isetekbd undo
```
or

```
:isetekbd default
```

This gives an error.

Even if you write `append` or `insert` in the help contents inside `vimrc`, it is the same error.

I'm not good at vimscript, so are you coding wrong?

I want to investigate the cause, but I don't have any knowledge.

And sorry for the terrible English.  thank you for reading!

**Comment by terrychou** [comment]
Thanks for reporting, I will look into it.

**Comment by terrychou** [comment]
It's been fixed, and the fix will be available in the upcoming update.

**Comment by terrychou** [comment]
version 2.10 is ready on App Store, check it out.

**Comment by pome-ta** [comment]
> version 2.10 is ready on App Store, check it out.

very cool bugfix and update!!!!
I love this application more.😍
