### ISSUE TITLE
Failure to open file on iCloud with apostrophe in file name 

### ISSUE THREAD

**Issue by emkayonline** [terrychou/iVim#84]
I have a markdown file with an apostrophe in the filename that used to load OK into ivim, but since version 2.1 I can't load it.

It will load if copied into the "On My iPhone/iVim" section in files, but not from an iCloud application folder (I've tried /iA Writer and /Desktop).

I've tried this with no .vim directory to ensure no plugins or customisation.

The filename has an apostrophe ' in it, and if I rename this and remove the character it will load from iCloud.

**Comment by terrychou** [comment]
Ok, I will have a look at it. Thanks for reporting.

**Comment by terrychou** [comment]
@emkayonline I tried to reproduce this problem but failed. I tried to rename a file in iCloud with a `'` in its name, or copy a file with `'` in its name to a iCloud folder. Both loaded OK.

Have you tried other files? Or can you provide the file in question for me to test?

**Comment by emkayonline** [comment]
I've created a new minimal file that reproduces the issue: [It's getting hot up here.txt](https://github.com/terrychou/iVim/files/4023256/It.s.getting.hot.up.here.txt)

Unfortunately it looks like GitHub renames the file on upload, so here is the original filename pasted here: It's getting hot up here.txt

To clarify the steps are:
1) Created text file with an apostrophe in filename in iA Writer on iCloud Drive
2) Ensure iVim has not .vimrc or .vim directory
3) In iVim used :idoc to open file from iA Writer folder on iCloud Drive
4) iVim hangs

If I copy the file to On My iPad/iVim then I can open the file.

Hope this helps.

**Comment by terrychou** [comment]
Emmm... it is weird that I can load this file too. 

However, I think I may know what the cause is. Please provide me an email, I will send you an invitation to test it via TestFlight.

**Comment by emkayonline** [comment]
That's great. Catch me on:
martin [at] live the seasons [dot] com
Thx

**Comment by terrychou** [comment]
Just for confirmation: is the middle part "livetheseasons"?

**Comment by emkayonline** [comment]
Sorry, yes.

**Comment by terrychou** [comment]
@emkayonline invitation sent.

**Comment by emkayonline** [comment]
It works. I can now open the files. Fantastic.
