### ISSUE TITLE
pip: command not found

### ISSUE THREAD

**Issue by kuochang** [terrychou/iVim#85]
I am new to iVim but I really like it. One thing bother me most is I don’t know how to use pip. I tried to type “:!pip install requests” in the command. It shows “pip: command not found”. Please help!

**Comment by terrychou** [comment]
You can use `:!python3 -m pip` to invoke `pip`. Or you can refer to this wiki entry: https://github.com/terrychou/iVim/wiki/External-Command:-python3#run-python-scripts-directly-as-commands

**Comment by kuochang** [comment]
Thanks a lot and it works! Actually I read the wiki but just didn’t realize I have to use ‘python3’ to invoke pip.:) Thanks again!

**Comment by terrychou** [comment]
No problem, enjoy.
