### ISSUE TITLE
enhanced mini keyboard support?

### ISSUE THREAD

**Issue by scottbolte** [terrychou/iVim#86]
I have an iPad mini which, unexpectedly, has turned out to be a very capable device when on the go. iVim, an external keyboard, iCloud files, blink with ssh, etc. are a powerful combo. The problem is the size of the keyboard and the all too common lack of an escape key. 

After trying a few others, I'm using a Logitech Focus keyboard (search for focus-keyboard-case-ipad-mini-4 to see a photo). It does the best it can, but given the size of the mini, there simply is not room for dedicated caps lock or escape keys. Therefore the traditional remapping of caps lock to escape is not an option.

I don't know enough about external keyboards to know if they share standard key codes. If they do, is it possible to remap Logitech's Home button (the square next to the space bar) or a modified key sequence such as caps-space or alt-space to escape?

**Comment by terrychou** [comment]
Nice mini keyboard but it looks like that it does not have a `ctrl` key?
Actually, vim has a default `esc` replacement: `ctrl + [`. Now that `ctrl` is not an option here, you may need to do the key mapping yourself. 

For example, to map `alt + space` to `esc` for insert mode: `:imap <A-Space> <Esc>`. (However, to enable `alt` key mapping, you need to switch on `Enable [alt] Mapping` for iVim in Settings.app)

Enjoy!

**Comment by scottbolte** [comment]
Thank you. I did not realize there was an `Enable [alt] Mapping` setting in the iOS preferences. That, plus adding the :imap line to my ~/.vimrc file, did the trick.
