### ISSUE TITLE
Repeat of external keyboard regular keys

### ISSUE THREAD

**Issue by steakknife** [terrychou/iVim#88]
Per side-comments of #3, external keyboard regular keys should repeat if `Accessibility > Keyboards > Hardware Keyboards > Key Repeat` is on. Without this, iVim is too inconvenient by being too different from desktop usage. IIRC, that's the reason I gave up on iVim last time (a couple of years ago). It seems like it's very close to being usable.

**Comment by terrychou** [comment]
I will add this option.

**Comment by terrychou** [comment]
and done, it will be available in the upcoming update.

**Comment by mchalkley** [comment]
@terrychou, this is awesome - thanks!

**Comment by mchalkley** [comment]
@terrychou, This enhancement is working perfectly in my installation - thank you again!

Mark

**Comment by terrychou** [comment]
@mchalkley no problem.

**Comment by idvorkin** [comment]
I have Key Repeat enabled in Accessibility - Key Repeat, as well as the option set in iVim settings, however I am not getting key repeat. 

How can I help debug?

@terrychou

**Comment by terrychou** [comment]
@idvorkin what is your configurations of hardware and software? Maybe you can give another hardware keyboard a try as the first approach.

**Comment by idvorkin** [comment]
I tried it again, changing nothing and it just worked - not sure what is going on.
