### ISSUE TITLE
How to clean up the key bindings of the uninstalled plugin in iVim?

### ISSUE THREAD

**Issue by kuochang** [terrychou/iVim#90]
I used to install some plugins in iVim and then I dislike them, so I deleted them. For somehow, iVim still remember those associated key bindings even I remove the plugins from all folders(auto load, plugins, bundles). Is there any way I can remove those key bindings from iVim. Thanks!

**Comment by terrychou** [comment]
If you have auto-restore enabled, it will remember global mappings. You can try to disable it to see if that helps.

**Comment by kuochang** [comment]
YES!!! It works!!! You’re the man! I almost wanted to reinstall everything and you save my day. Thanks!!!
