### ISSUE TITLE
Keyboard focus not returning to iVim  in split screen

### ISSUE THREAD

**Issue by emkayonline** [terrychou/iVim#91]
When using iVim in 50-50 split screen on an iPad Pro with an external keyboard, it seems that iVim can only get keyboard focus when the extended keyboard is visible.

To reproduce this:
1) Open iVim and another app that accepts keyboard input (eg. Drafts) in a 50-50 split on the iPad
2) Make sure the extended keyboard is hidden in iVim
3) Using an external keyboard, type something into Drafts
4) Now tap on iVim to change focus. And type on the external keyboard
- At this point focus stays with Drafts not iVim, ie. the keypresses appear in Drafts

A workaround is to bring up the extended keyboard and hide it again, but it would be nice not to have to do that every time.

**Comment by terrychou** [comment]
It’s been fixed and I am pushing it to TestFlight.

**Comment by emkayonline** [comment]
I've just been testing it and it works perfectly.  Thank you.
