### ISSUE TITLE
Support zooming via Win+ Win- and pinch motions

### ISSUE THREAD

**Issue by idvorkin** [terrychou/iVim#94]
While not strictly a vim command, this is a features of most terminals, so folks would love it.  Might be a good "pay-for" feature as well.

**Comment by terrychou** [comment]
I will think about it.

**Comment by terrychou** [comment]
The version 2.15 added two fingers pinch to zoom. However, it doesn't include the hardcoded keyboard shortcuts (like you mentioned as `Win +` or `Win -`). Instead, two subcommands `+` and `-` have been added to command `:ifont` to change the current font size. You can map them to any key pressing as you like.

**Comment by NightMachinary** [comment]
@terrychou How do I persist the font size between relaunchs?

**Comment by terrychou** [comment]
@NightMachinary If you have enabled the auto-restore, it should restore the font size between relaunches automatically; otherwise, you can put `ifont _ 20` (`20` here is the font size) into your `.vimrc` file.

**Comment by NightMachinary** [comment]
@terrychou How do I enable the auto restore?

**Comment by terrychou** [comment]
@NightMachinary Please refer to `:help ios-settings`
