### ISSUE TITLE
Can we hide the home bar on iOS 13?

### ISSUE THREAD

**Issue by dangh** [terrychou/iVim#98]
Hello,

As the title say, is there any way to do it? It’s occupied the bottom real estate and very annoying when we use a dark theme.

Also, thank you for this awesome app. I’m very happy to support it ❤️

**Comment by terrychou** [comment]
By "home bar", do you mean the extended keyboard bar? If so, single finger long touch the screen will toggle it; or you can make it hidden by default by switching on the related option in the Settings.app.

**Comment by dangh** [comment]
I mean the white stripe in the screen shot. I’m not sure what to call it 😛

![IMG_0038](https://user-images.githubusercontent.com/1020347/76676577-f7ff7000-65ff-11ea-91c3-3dfb783725f9.jpeg)

**Comment by terrychou** [comment]
I see, I will look into it.

**Comment by terrychou** [comment]
The latest update (version 2.15) provides an option in the Settings app to do this. It is disabled by default though.
